### ISSUE TITLE
Button handlers stop working when `enablePackageExports` flag is true

### ISSUE THREAD

**Issue by jgalat** [tamagui/tamagui#1918] opened 2023-11-27 16:14 UTC
### Current Behavior

On our project we are in need to enable the `unstable_enablePackageExports` flag on Metro. This disables all `onPress` callbacks in Tamagui buttons from our app

### Expected Behavior

Callbacks in `onPress` prop in Tamagui buttons should be called

### Tamagui Version

```markdown
1.79.1
```

### Platform (Web, iOS, Android)

```markdown
Issue on Android.
Web works fine.
We are unable to test on iOS yet.
```

### Reproduction

```markdown
Here you can find a minimal reproduction repository

https://github.com/jgalat/tamagui-unstable-repro

The reproduction uses `bun` but feel free to use any package manager.
Install with `bun i`, run with `bun start` and check the issue on Expo GO (App or Emulator on Android).
There are 2 sets of buttons (Tamagui vs React Native). On React Native ones the callbacks work
```

### System Info

```markdown
System:
    OS: Linux 6.1 Gentoo Linux
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-1280P
    Memory: 25.24 GB / 31.01 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    bun: 1.0.12 - ~/.bun/bin/bun
```

**Comment by zgid123** [comment] 2023-12-10 18:26
I use Sheet and when touch outside, it does not close the modal too

**Comment by natew** [comment] 2024-01-02 21:27
Super weird, I looked into it. My guess is its not resolving `.native`. file extensions somehow when used, can you check if this is a known issue in expo?

**Comment by natew** [comment] 2024-01-02 21:44
Fix in 1000aac29f480ed2deca500ed84c8b3764c9f053 and c53dbbd9ea75002fe1622e0073825b3c272a51ae

Turns out they changed the behavior a bit when dealing with exports.

**Closed** 2024-01-03 18:01 UTC

**Comment by cruzdanilo** [comment] 2024-01-17 00:57
i'm still having the same issue here. how can i help debugging?

**Comment by natew** [comment] 2024-01-17 03:23
Can you set up a reproduction? In the monorepo we also have starters/expo-router where you could try setting it up there

**Comment by jgalat** [comment] 2024-01-17 13:49
Hi @natew thanks for taking the time to look into this

I just upgraded the original reproduction [repo](https://github.com/jgalat/tamagui-unstable-repro) to 1.86.4 and the issue is still reproducible

**Comment by christophehurpeau** [comment] 2024-03-24 17:26
`react-native` should be moved above `require` as fields are prioritized based on the exports field in the package.json, not the conditionnames https://metrobundler.dev/docs/package-exports#replacing-browser-and-react-native-fields

> Under "exports", packages concretely define the resolution order for conditional entry points

If you are opened to a PR I can probably make one next week ?
