### ISSUE TITLE
Select does not visually update when value changes from outside the component

### ISSUE THREAD

**Issue by hackily** [tamagui/tamagui#1843] opened 2023-11-06 19:26 UTC
### Current Behavior

Select does not visually update value when the value changes.

https://github.com/tamagui/tamagui/assets/8202335/85239964-9187-496f-b4e1-5fb1c2a95e50

### Expected Behavior

When value changes, select should visually reflect the value state. This is important for resetting forms, or when state is hydrated later, such as after an api call.

### Tamagui Version

```markdown
1.76.0
```

### Platform (Web, iOS, Android)

```markdown
Web
Didn't test ios/android
```

### Reproduction

```markdown
https://codesandbox.io/p/sandbox/gallant-hooks-hzrxt4?file=%2Fpackages%2Fapp%2Ffeatures%2Fhome%2Fscreen.tsx%3A13%2C16
```

### System Info
```
  System:
    OS: Linux 6.1 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD EPYC
    Memory: 104.06 MB / 2.01 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 3.6.3 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 20220528.183901.0 - /usr/local/bin/watchman
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.21.0 
    @manypkg/cli: ^0.19.1 => 0.19.2 
    check-dependency-version-consistency: ^3.0.3 => 3.0.3 
    eslint: ^8.21.0 => 8.39.0 
    node-gyp: ^9.3.1 => 9.3.1 
    prettier: ^2.7.1 => 2.8.8 
    turbo: ^1.10.3 => 1.10.3 
    typescript: ^4.9.4 => 4.9.5 
    ```

**Comment by sakhnyuk** [comment] 2023-11-08 09:13
Same issue

**Comment by Farmacist-Dylan** [comment] 2023-11-09 02:53
Also having this issue

**Comment by AlexCyphus** [comment] 2023-11-16 16:41
+1

**Comment by satoren** [comment] 2023-12-11 00:17
https://github.com/tamagui/tamagui/issues/1928

**Comment by natew** [comment] 2023-12-14 19:52
This should be fixed as of last release, I updated the logic there. Lmk if not.

**Closed by natew** 2023-12-14 19:52 UTC

**Comment by MusabDev** [comment] 2025-07-27 00:06
The issue is still not fixed as of now.

**Comment by natew** [comment] 2025-07-27 03:41
Can you update the reproduction to use latest packages? We use select all over the place without issue so it must be some specific thing.
