### ISSUE TITLE
[bug] `unstyled` still applies `focusStyle` and `hoverStyle`

### ISSUE THREAD

**Issue by nandorojo** [tamagui/tamagui#763] opened 2023-03-06 23:43 UTC
If you wrap `TextInput` with `styled`, `focusStyle` and `hoverStyle` still apply, even after setting `unstyled={true}`. 

Lmk if we need a repro. I can try to set up a Stackblitz starter to make repros easier.

**Comment by seeden** [comment] 2023-03-07 07:55
maybe related to https://github.com/tamagui/tamagui/issues/725 as well

**Comment by nandorojo** [comment] 2023-03-09 15:23
Here is a [reproduction](https://codesandbox.io/p/github/nandorojo/tamagui-starter/unstyled-repro?file=%2Fapps%2Fnext%2Fpages%2Findex.tsx&workspaceId=35a4fe1b-7440-42d4-b5e7-e00c1af26e95&selection=%5B%7B%22endColumn%22%3A81%2C%22endLineNumber%22%3A11%2C%22startColumn%22%3A81%2C%22startLineNumber%22%3A11%7D%5D).


<img width="774" alt="Screenshot 2023-03-09 at 10 23 04 AM" src="https://user-images.githubusercontent.com/13172299/224070567-c7fc8458-02e4-4c81-93c0-862ab2755f6f.png">

```tsx
import { Input, styled, Text, Stack } from 'tamagui'

const TextInput = styled(Input)

export default function Repro() {
  return (
    <Stack gap="$4" p={32} flex={1} bg="$color1">
      <Text color="$color11" fontFamily="$body">
        This input respects the unstyled prop. Focusing it doesn't do anything weird.
      </Text>
      <Input bg="$color3" placeholder="This input works" p={16} unstyled color="$color11" />

      <Text color="$color11" fontFamily="$body">
        This input does not respect the unstyled prop. <code>unstyled.false.focusStyle</code> still
        applies.
      </Text>
      <TextInput bg="$color4" placeholder="here is another input" unstyled />
    </Stack>
  )
}
```

**Comment by natew** [comment] 2023-03-18 21:55
Looking at this now.

**Comment by natew** [comment] 2023-03-18 21:55
Also heads up 

<img width="797" alt="CleanShot 2023-03-18 at 11 55 46@2x" src="https://user-images.githubusercontent.com/12100/226142368-af324be6-a28a-4346-8711-c86997b51293.png">

**Comment by nandorojo** [comment] 2023-03-18 22:05
ah sorry this was before i figured out the better way to do a repro

**Comment by natew** [comment] 2023-03-18 22:15
No worries. I think I have a fix, testing it across platforms now.

**Comment by natew** [comment] 2023-03-19 09:41
Let me know if the latest release fixes.

**Comment by seeden** [comment] 2023-03-19 12:15
Hi @natew. The latest version 1.7.9 did not fix the focusStyle issue. It also brings new issues. Fox example padding stopped working as well

**Comment by seeden** [comment] 2023-03-19 16:07
I prepared also repo where you can see both issues

https://github.com/seeden/tamagui-focus-order-issue

1. you are not able to change borderWidth  with focusStyle
2.  padding is completely broken when you use styled

How to reproduce it
```sh
git clone https://github.com/seeden/tamagui-focus-order-issue
npm install
npm run dev

open: localhost:3000
```

**Comment by natew** [comment] 2023-03-26 02:43
Checking this now

**Comment by natew** [comment] 2023-03-26 03:04
Ok this was a separate issue with the static optimizer, next patch release has a fix. Thanks for the repro.

**Comment by seeden** [comment] 2023-03-26 19:52
Meanwhile I used my own defaultStyles

```tsx
const defaultStyles = {
  size: '$true',
  fontFamily: '$body',
  borderWidth: 0,
  outlineWidth: 0,
  color: '$color',
  focusable: true,
  borderColor: 'transparent',
  backgroundColor: 'transparent',
  placeholderTextColor: '$color9',

  // this fixes a flex bug where it overflows container
  minWidth: 0,

  hoverStyle: {
    borderColor: 'transparent',
  },

  focusStyle: {
    borderColor: 'transparent',
    borderWidth: 0,
  },
} as const;


const StyledInput = styled(InputBase, {
  ...defaultStyles,
  variants: {
    unstyled: {
      false: defaultStyles,
    },
});
```

**Comment by natew** [comment] 2023-03-27 01:07
Btw to if it’s the compiler you can always work around it by using // tamagui-ignore at the top just so it doesn’t block you. Is this latest code snippet enough to repro the remaining issue?

**Comment by seeden** [comment] 2023-03-27 12:13
I will need to prepare new repo because I need to know which part of my application is doing it. I will try to prepare it during the weekend.

**Comment by seeden** [comment] 2023-04-20 18:43
Sorry for the delay. I was sick. It is still broken in the latest version 1.15.23 .
I will try to prepare testing repo during weekend again

**Comment by natew** [comment] 2023-04-20 23:00
We have a great test setup now so I’ll take this one on soon. Hope you feel better @seeden

**Comment by natew** [comment] 2023-04-20 23:55
I can't repro it, tried with and without compiler:

<img width="1588" alt="CleanShot 2023-04-20 at 13 55 13@2x" src="https://user-images.githubusercontent.com/12100/233510109-201394eb-2d65-4151-866a-a3ea4751d17d.png">

**Comment by natew** [comment] 2023-04-21 20:42
@seeden please lmk if broken but closing for now as we have a test case in place

**Closed by natew** 2023-04-21 20:42 UTC
