### ISSUE TITLE
defaultVariant go before other props in styled if parent doesn't use them

### ISSUE THREAD

**Issue by mfazekas** [tamagui/tamagui#2720] opened 2024-06-12 16:46 UTC
### Current Behavior

```js
const Circle2 = styled(View, {
   backgroundColor: "green",
   variants: {
    variant: {
      blue: {
        backgroundColor: "blue",
      },
    },
  },
  defaultVariants: {
    variant: "blue",
  },
})
```
causes `<Circle2 />` to be rendered as "green" instead of `blue`. 
see:
https://codesandbox.io/p/sandbox/eager-leaf-8sv56h?file=%2Fsrc%2FApp.tsx

### Expected Behavior

I'd expect `defaultVariants` to override props in styled. (But my expectations might be wrong.) They do behave this way in case parent component has the same props.

See `CircleBase` and `Circle` in the sandbox.

```jsx
const CircleBase = styled(View, {
  ...
  backgroundColor: "red",
});

const Circle = styled(CircleBase, {
  backgroundColor: "green",
  variants: {
    variant: {
      blue: {
        backgroundColor: "blue",
      },
    },
  },
  defaultVariants: {
    variant: "blue",
  },
} as const);
```

A `<Circle />` will be rendered as blue.

For Circle Object.entries(staticConfig.defaultProps) looks like this:
```
[
    ...
    [
        "backgroundColor",
        "green"
    ],
    [
        "variant",
        "blue"
    ]
]
```

while for Circle2 Object.entries(staticConfig.defaultProps) looks like this:
```
    ...
    [
        "variant",
        "blue"
    ]
    ...
    [
        "backgroundColor",
        "green"
    ],
```

See also [`fix(web): fix defaultVariants should go behind other props inside styled() but above parent styled props and defaultVariants`](https://github.com/tamagui/tamagui/commit/f7edcd691601d6bca0c882e34d795e552b206706)

### Tamagui Version

```markdown
1.100.3
```

### Platform (Web, iOS, Android)

```markdown
web
```

### Reproduction

```markdown
https://codesandbox.io/p/sandbox/eager-leaf-8sv56h?file=%2Fsrc%2FApp.tsx
```

### System Info

```markdown
Chrome Version 125.0.6422.142 (Official Build) (arm64) on MacOS X
```

**Comment by natew** [comment] 2024-07-20 00:54
Agree and fixed in d7b6d2cd11f805f3abc77bbb8996d689bc48a85b

I found it to be a pretty safe change, tested across a few apps and no regressions due to the change.

**Closed by natew** 2024-07-20 00:54 UTC
