### ISSUE TITLE
[bug] sheets gets blank on input focus (native expo)

### ISSUE THREAD

**Issue by patcito** [tamagui/tamagui#601] opened 2023-01-28 14:19 UTC
Happens on native android at least. Focusing on input text inside a sheet dialog makes the whole sheet go blank.

**To Reproduce**
Just paste the example from the doc https://tamagui.dev/docs/components/dialog/1.0.0
Run on expo android for example, open the dialog and press on the Name input
Sheet goes blank

Demo:
https://user-images.githubusercontent.com/26435/215271937-b10db209-b846-417f-b7e3-b46b7718d7e8.mp4

**System Info:** 

Output of `npx envinfo --system --npmPackages --binaries --browsers`
System:                                                                                                                                               
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)                                                                                     
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz                                                                                         
    Memory: 1.63 GB / 31.06 GB                                                                                                                          
    Container: Yes                                                                                                                                      
    Shell: 5.1.16 - /bin/bash                                                                                                                           
  Binaries:                                                                                                                                             
    Node: 19.3.0 - ~/.nvm/versions/node/v19.3.0/bin/node                                                                                                
    Yarn: 3.2.3 - ~/.nvm/versions/node/v19.3.0/bin/yarn                                                                                                 
    npm: 9.2.0 - ~/.nvm/versions/node/v19.3.0/bin/npm                                                                                                   
  Browsers:                                                                                                                                             
    Brave Browser: beta
    Chrome: 108.0.5359.124
    Firefox: 109.0
  npmPackages:
   @babel/plugin-proposal-export-namespace-from: ^7.18.9 => 7.18.9 
    @babel/runtime: ^7.18.9 => 7.20.7  
    @ethersproject/providers: ^5.7.2 => 5.7.2 
    @ethersproject/shims: ^5.7.0 => 5.7.0 
    @expo/vector-icons: ^13.0.0 => 13.0.0 
    @expo/webpack-config: ^0.17.2 => 0.17.4 
    @gnosis.pm/safe-modules-deployments: ^1.0.0 => 1.0.0 
    @gnosis.pm/safe-react-gateway-sdk: ^3.5.2 => 3.5.2 
    @manypkg/cli: ^0.19.1 => 0.19.2 
    @react-native-async-storage/async-storage: ^1.17.11 => 1.17.11 
    @safe-global/safe-core-sdk-types: ^1.8.0 => 1.8.0 
    @safe-global/safe-gateway-typescript-sdk: ^3.5.5 => 3.5.5 
    @tanstack/query-async-storage-persister: ^4.22.4 => 4.22.4 
    @tanstack/react-query: ^4.22.4 => 4.22.4 
    @tanstack/react-query-persist-client: ^4.22.4 => 4.22.4 
    atob: ^2.1.2 => 2.1.2 
    base-64: ^1.0.0 => 1.0.0 
    date-fns: ^2.29.3 => 2.29.3 
    eslint: ^8.21.0 => 8.31.0 
    ethers: ^5.7.2 => 5.7.2 
    expo-barcode-scanner: ^12.1.0 => 12.2.0 
    expo-camera: ^13.1.0 => 13.1.0 
    expo-constants: ^14.0.2 => 14.1.0  
    expo-modules-core: ^1.1.1 => 1.1.1  
    node-libs-react-native: ^1.2.1 => 1.2.1 
    prettier: ^2.7.1 => 2.8.2 
    react-hook-form: ^7.42.1 => 7.42.1  
    react-native-get-random-values: ^1.8.0 => 1.8.0 
    react-native-svg-transformer: ^1.0.0 => 1.0.0 
    semver: ^7.3.8 => 7.3.8 
    turbo: ^1.4.2 => 1.7.0 
    typescript: ^4.7.4 => 4.9.4 
    wagmi: ^0.10.10 => 0.10.10

**Comment by patcito** [comment] 2023-01-31 21:02
tested in latest version and it's fixed so closing this. Thanks!

**Comment by patcito** [comment] 2023-01-31 21:06
nvm, still happening

**Comment by patcito** [comment] 2023-01-31 21:19
To be precise, it doesn't happen anymore when I remove the <Adapt /> tag from the dialog

```
-      <Adapt when="sm" platform="touch">
-        <Sheet zIndex={200000} modal dismissOnSnapToBottom>
-          <Sheet.Frame padding="$4" space>
-            <Adapt.Contents />
-          </Sheet.Frame>
-          <Sheet.Overlay />
-        </Sheet>
-      </Adapt>
-
```

**Comment by lobor** [comment] 2023-02-04 07:17
if you add this on your Input ?

```typescript
<Input
  onFocus={(e) => e.stopPropagation()}
  ...
/>
```
I know that is not good solution but work and is not blocking

**Comment by Dolu89** [comment] 2023-02-09 13:17
Hello, same issue here, with the documentation code exemple (like @patcito)

@lobor Your solution doesn't work on my app.
@patcito What do you mean by removing tag from the dialog?

**Comment by nderscore** [comment] 2023-02-17 21:00
I recently encountered another variation of this issue in my app. In my case, instead of an `<Input>` inside of a Sheet, I have a [`<WebView>`](https://github.com/react-native-webview/react-native-webview) inside a Sheet containing a page with a text input.

As soon as the user focuses on an input in the webview and the keyboard appears, the webview refreshes itself -- behaving almost as if that instance of the component had been invalidated by a new `key` prop.

I'm only able to reproduce this issue on Android (not on iOS) and only when the sheet has the `modal` property set to `true`. Non-modal sheets behave normally on all platforms.

This makes me think that the problem is somehow related to the custom native implementation of portal (`@tamagui/portal`->`Portal.native.tsx`)? Still just a hunch at this stage though. I'm going to try to find some time to dig a bit deeper into finding out what ultimately is the root cause(s).

**Comment by RobynVG** [comment] 2023-02-22 17:39
Hey there,

Similar to what @nderscore reported.

I'm using <Input> inside of a Sheet. When the input is focused the keyboard appears, the sheet shifts up on the screen and shortly after (with no further interactions) it resets: keyboard closes + the sheet shifts back down.

I would agree that the issue occurs "when the sheet is in a flex container which flex-grows to the height of the screen". Wrapping the sheet in a Stack with the height set to the height of the window completely resolves the issue. 

Tested on android

**Comment by aliansyahFirdaus** [comment] 2023-02-25 04:02
yeah same issue here, when putting the input text in the sheet

**Comment by aliansyahFirdaus** [comment] 2023-02-25 07:44
temporarily you can add this in expo configuration (app.json / expo.json)

```
    "android": {
      "softwareKeyboardLayoutMode":"pan"
    }
```

**Comment by natew** [comment] 2023-04-21 20:45
I think we added some docs on how to avoid this on the Sheet docs page in a different way too (if I understand correctly).

@nderscore let me know if you found anything here.

**Comment by nderscore** [comment] 2023-04-21 20:57
@natew The sheet being blanked was caused by the sheet conditionally un-mounting its contents during a resize. 

That's been fixed in #787

---

I think the only other concern here was how to handle keyboard avoiding for `<Sheet modal>`

I saw that `moveOnKeyboardChange` was added as a Sheet prop recently, which I believe solves for that case, but admittedly I haven't tested it out yet. For my use case, I ended up using a non-modal sheet and doing my own keyboard avoiding on the parent container.

**Comment by jmurphy4** [comment] 2023-04-26 15:28
https://user-images.githubusercontent.com/6276406/234624861-68b4dc61-1d1d-4c74-9f27-b2f0623a8f37.mov

So i currently have an input in a dialog, when modal is set to true. I get what is shown in the video, when I set modal to false its completely fine.

**Comment by natew** [comment] 2023-09-10 21:53
i think this is fixed, but re-open with new repro if that other issue still exists

**Closed by natew** 2023-09-10 21:53 UTC
