### ISSUE TITLE
Tamagui throws error when using Expo 51 New Arch

### ISSUE THREAD

**Issue by erwanlpfr** [tamagui/tamagui#2633] opened 2024-05-08 13:59 UTC
### Current Behavior

Hello ! 

Today, with the Expo 51 release, I tried the new arch.
As you can see in the files, Tamagui is set as inspired by this : https://github.com/ivopr/tamagui-expo
So by activating the new arch, I can this right after the JS bundle starting the following logs.

Maybe something changed or has to be changed with the new arch.
If I am not the only one, maybe we could provide more demo ?

Thank you for your work !

### Tamagui Version

```markdown
^1.97.1
```

### Platform (Web, iOS, Android)

```markdown
on iOS and Android


iOS Bundled 2132ms node_modules/expo-router/entry.js (3191 modules)
 (NOBRIDGE) LOG  Bridgeless mode is enabled
 (NOBRIDGE) ERROR  TypeError: Cannot read property 'add' of undefined

This error is located at:
    in PortalHostComponent (created by ToastViewport)
    in RCTView (created by ToastViewport)
    in ToastViewport (created by Slot)
    in Slot (created by ToastCollectionSlot)
    in ToastCollectionSlot (created by ToastViewport)
    in RCTView (created by ViewportWrapper)
    in ViewportWrapper (created by ToastViewport)
    in ToastViewport (created by ToastViewport)
    in ToastImperativeProvider (created by ToastProvider)
    in Provider (created by ToastProvider)
    in Provider (created by CollectionProvider)
    in CollectionProvider (created by ToastProvider)
    in ToastProvider (created by ToastProvider)
    in ToastProvider (created by Layout)
    in ThemeProvider (created by InternalThemeProvider)
    in Theme (created by InternalThemeProvider)
    in InternalThemeProvider (created by GlobalThemeProvider)
    in PortalProviderComponent (created by TamaguiProvider)
    in Theme (created by ThemeProvider)
    in ThemeProvider (created by TamaguiProvider)
    in Provider (created by TamaguiProvider)
    in TamaguiProvider (created by TamaguiProvider)
    in TamaguiProvider (created by GlobalThemeProvider)
    in GlobalThemeProvider (created by Layout)
    in Provider (created by Layout)
    in I18nProvider (created by Layout)
    in Layout
    in Unknown (created by Route())
    in Suspense (created by Route())
    in Route (created by Route())
    in Route() (created by ContextNavigator)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by wrapper)
    in wrapper (created by ContextNavigator)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay (created by withDevTools(ErrorOverlay))
    in withDevTools(ErrorOverlay)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
 (NOBRIDGE) ERROR  TypeError: Cannot read property 'add' of undefined

This error is located at:
    in PortalHostComponent (created by PortalProviderComponent)
    in PortalProviderComponent (created by TamaguiProvider)
    in Theme (created by ThemeProvider)
    in ThemeProvider (created by TamaguiProvider)
    in Provider (created by TamaguiProvider)
    in TamaguiProvider (created by TamaguiProvider)
    in TamaguiProvider (created by GlobalThemeProvider)
    in GlobalThemeProvider (created by Layout)
    in Provider (created by Layout)
    in I18nProvider (created by Layout)
    in Layout
    in Unknown (created by Route())
    in Suspense (created by Route())
    in Route (created by Route())
    in Route() (created by ContextNavigator)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by wrapper)
    in wrapper (created by ContextNavigator)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay (created by withDevTools(ErrorOverlay))
    in withDevTools(ErrorOverlay)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
 (NOBRIDGE) ERROR  TypeError: Cannot read property 'add' of undefined

This error is located at:
    in PortalHostComponent (created by ToastViewport)
    in RCTView (created by ToastViewport)
    in ToastViewport (created by Slot)
    in Slot (created by ToastCollectionSlot)
    in ToastCollectionSlot (created by ToastViewport)
    in RCTView (created by ViewportWrapper)
    in ViewportWrapper (created by ToastViewport)
    in ToastViewport (created by ToastViewport)
    in ToastImperativeProvider (created by ToastProvider)
    in Provider (created by ToastProvider)
    in Provider (created by CollectionProvider)
    in CollectionProvider (created by ToastProvider)
    in ToastProvider (created by ToastProvider)
    in ToastProvider (created by Layout)
    in ThemeProvider (created by InternalThemeProvider)
    in Theme (created by InternalThemeProvider)
    in InternalThemeProvider (created by GlobalThemeProvider)
    in PortalProviderComponent (created by TamaguiProvider)
    in Theme (created by ThemeProvider)
    in ThemeProvider (created by TamaguiProvider)
    in Provider (created by TamaguiProvider)
    in TamaguiProvider (created by TamaguiProvider)
    in TamaguiProvider (created by GlobalThemeProvider)
    in GlobalThemeProvider (created by Layout)
    in Provider (created by Layout)
    in I18nProvider (created by Layout)
    in Layout
    in Unknown (created by Route())
    in Suspense (created by Route())
    in Route (created by Route())
    in Route() (created by ContextNavigator)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by wrapper)
    in wrapper (created by ContextNavigator)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay (created by withDevTools(ErrorOverlay))
    in withDevTools(ErrorOverlay)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
```

### Reproduction

```markdown
Here the config : 


import { config as tamaguiConfig } from '@tamagui/config/v3';
import { createInterFont } from '@tamagui/font-inter';
import { createTamagui } from 'tamagui';

const config = createTamagui({
  ...tamaguiConfig,
  reactNative: true,
  defaultTheme: 'light',
  defaultFont: 'body',
  fonts: {
    heading: createInterFont({
      family: 'Poppins_700Bold',
    }),
    body: createInterFont({
      family: 'Popins_100Thin',
    }),
  },
});

export default config;


```json
{
  "name": "app",
  "version": "1.0.0",
  "license": "MIT",
  "main": "expo-router/entry",
  "scripts": {
    "start": "expo start",
    "lint": "biome check .",
    "dev:android": "expo run:android",
    "dev:ios": "expo run:ios",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "prepare": "husky"
  },
  "dependencies": {
    "@lingui/react": "^4.10.1",
    "@reduxjs/toolkit": "^2.2.3",
    "@rnmapbox/maps": "^10.1.21",
    "@tamagui/animations-moti": "^1.97.1",
    "@tamagui/babel-plugin": "^1.97.1",
    "@tamagui/config": "^1.97.1",
    "@tamagui/font-inter": "^1.97.1",
    "@tamagui/lucide-icons": "^1.97.1",
    "@tamagui/sheet": "^1.97.1",
    "@tamagui/theme-base": "^1.97.1",
    "@tamagui/themes": "^1.97.1",
    "@tamagui/toast": "^1.97.1",
    "@turf/turf": "7.0.0-alpha.116",
    "burnt": "^0.12.2",
    "expo": "^51.0.0",
    "expo-build-properties": "~0.12.1",
    "expo-dev-client": "~4.0.11",
    "expo-font": "~12.0.4",
    "expo-localization": "~15.0.3",
    "expo-location": "~17.0.1",
    "expo-router": "~3.5.10",
    "expo-system-ui": "~3.0.4",
    "expo-task-manager": "~11.8.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.1",
    "react-native-gesture-handler": "^2.16.2",
    "react-native-reanimated": "^3.11.0",
    "react-native-safe-area-context": "4.10.1",
    "react-native-screens": "3.31.1",
    "react-native-svg": "15.2.0",
    "react-redux": "^9.1.2",
    "redux-persist": "^6.0.0",
    "tamagui": "^1.97.1"
  },
  "devDependencies": {
    "@babel/core": "^7.24.5",
    "babel-plugin-macros": "^3.1.0",
    "@biomejs/biome": "^1.7.3",
    "@commitlint/cli": "^19.3.0",
    "@commitlint/config-conventional": "^19.2.2",
    "@lingui/cli": "^4.10.1",
    "@lingui/macro": "^4.10.1",
    "@types/react": "~18.2.45",
    "husky": "^9.0.11",
    "semantic-release": "^23.0.8",
    "typescript": "~5.3.3"
  }
}
```

With Expo Plugins : 

```ts
      'expo-localization',
      [
        'expo-build-properties',
        {
          ios: {
            newArchEnabled: true,
          },
          android: {
            newArchEnabled: true,
          },
        },
      ],
```

And with a layout file at the root that looks like that : 

```ts
import { ThemeProvider } from '@react-navigation/native';
import { useColorScheme } from 'react-native';
import { TamaguiProvider, Theme, useTheme } from 'tamagui';
import config from '../../../tamagui.config';

export const InternalThemeProvider = ({ children }: React.PropsWithChildren) => {
  const colorScheme = useColorScheme();
  const simplifiedColorScheme = colorScheme === 'dark' ? 'dark' : 'light';
  const theme = useTheme({
    name: simplifiedColorScheme,
  });

  const NavigationTheme: React.ComponentProps<typeof ThemeProvider>['value'] = {
    dark: simplifiedColorScheme === 'dark',
    colors: {
      primary: theme.color.val,
      background: theme.background.val,
      card: theme.background.val,
      text: theme.color.val,
      border: theme.borderColor.val,
      notification: theme.color.val,
    },
  };

  return (
    <Theme name={simplifiedColorScheme}>
      <ThemeProvider value={NavigationTheme}>{children}</ThemeProvider>
    </Theme>
  );
};

export function GlobalThemeProvider({ children }: React.PropsWithChildren) {
  return (
    <TamaguiProvider config={config}>
      <InternalThemeProvider>{children}</InternalThemeProvider>
    </TamaguiProvider>
  );
}
```
```


### System Info

_No response_

**Comment by kvaster** [comment] 2024-05-09 06:20
We experiancing same problem with tamagui and 'PortalHostComponent' when trying to migrate to new architecture.

**Comment by sync** [comment] 2024-05-09 11:24
you can temporarily fix it by patching this file: 

`node_modules/@tamagui/portal/dist/cjs/GorhomPortal.native.js`

And change this method on line 182:

from
```js
    var next = function(value) {
      (0, import_react.startTransition)(function() {
        dispatch(value);
      });
    };

```

to
```js
    var next = function(value) {
        dispatch(value);
    };
```

**Comment by sync** [comment] 2024-05-10 02:39
[@tamagui+portal+1.97.1.patch.zip](https://github.com/tamagui/tamagui/files/15269721/%40tamagui%2Bportal%2B1.97.1.patch.zip)

you can use this patch with patch-package

**Comment by nicolasartman** [comment] 2024-05-10 04:05
Amazing, thank you so much @sync! I yarn-patched those lines out and builds are working again for me.

**Comment by kvaster** [comment] 2024-05-10 08:08
I've tried this patch, but it doesn't work for me :(

I'm having this error on Android build:

```
 (NOBRIDGE) ERROR  TypeError: Cannot read property 'add' of undefined

This error is located at:
    in PortalHostComponent (created by PortalProviderComponent)
    in PortalProviderComponent (created by TamaguiProvider)
    in Theme (created by ThemeProvider)
    in ThemeProvider (created by TamaguiProvider)
    in Provider (created by TamaguiProvider)
    in TamaguiProvider (created by TamaguiProvider)
    in TamaguiProvider (created by Application)
    in Application (created by _default)
    in _default
    in Unknown (created by Route())
    in Suspense (created by Route())
    in Route (created by Route())
    in Route() (created by ContextNavigator)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by wrapper)
    in wrapper (created by ContextNavigator)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay (created by withDevTools(ErrorOverlay))
    in withDevTools(ErrorOverlay)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
```

**Comment by natew** [comment] 2024-05-13 02:22
Have a fix in main for this will get it out today. Wonder why transition would break it, weird?

**Comment by sync** [comment] 2024-05-13 03:05
weird indeed

**Comment by natew** [comment] 2024-05-13 04:48
Fixed in https://github.com/tamagui/tamagui/releases/tag/v1.98.0

**Comment by contactsimonwilson** [comment] 2024-05-15 06:10
@kvaster same here

For me it seems to be breaking on any use of the Switch component

**Comment by sync** [comment] 2024-05-15 07:15
yes @kvaster, @natew it is once more startTransition messing things, can reproduce on touch if Switch component is enabled: 

this code: 

```
      const [checked, setChecked] = useControllableState({
        prop: checkedProp,
        defaultProp: defaultChecked || false,
        onChange: onCheckedChange,
        transition: true,
      })

```

can be fixed if changed to: 

```
      const [checked, setChecked] = useControllableState({
        prop: checkedProp,
        defaultProp: defaultChecked || false,
        onChange: onCheckedChange,
        transition: false,
      });

```

There is really something funky with `startTransition` happening somewhere.

**Comment by sync** [comment] 2024-05-15 07:24
Probably one of the `.add` in there https://github.com/facebook/react-native/blob/main/packages/react-native/Libraries/Renderer/implementations/ReactFabric-prod.js

**Comment by sync** [comment] 2024-05-15 11:37
crashing here inside the dev renderer

<img width="838" alt="Screenshot 2024-05-15 at 8 37 18 PM" src="https://github.com/tamagui/tamagui/assets/21725/056cd12f-7d45-4403-b200-46fd4a269e1a">

**Comment by sync** [comment] 2024-05-15 11:56
Just a temp fix but you can patch the renderer to check if set is defined before adding to it

[react-native+0.74.1.patch.zip](https://github.com/tamagui/tamagui/files/15321045/react-native%2B0.74.1.patch.zip)

**Comment by sync** [comment] 2024-05-15 12:25
Will look at upstreaming this to rn if it makes sense and then we can should be fine with `startTransition`

**Comment by sync** [comment] 2024-05-15 23:41
pr here: https://github.com/facebook/react-native/pull/44586

**Comment by corasan** [comment] 2024-06-27 00:48
I am still experiencing this, tamagui `v1.101.3` on Expo SDK 51 with newArch enabled.

**Comment by sync** [comment] 2024-06-27 00:57
@corasan using the manual patch for react-native ? the have updated their renderer in 0.75.x so hopefully it will go away once expo 52 drops in, which could be far away

**Comment by CatStudioApp** [comment] 2024-06-27 19:47
> facebook/react-native#44586

I can confirm on 0.75 rc2 there's no such a problem anymore

**Comment by imWildCat** [comment] 2024-06-27 19:56
post install patch script
```bash
#!/bin/bash

if [[ "$OSTYPE" == "msys" ]]; then
  echo "This script is not supported on Windows"
  exit 0
fi

# after React Native 0.75.x, you can remove this 

zip_url="https://github.com/tamagui/tamagui/files/15327852/react-native%2B0.74.1.patch.zip"

echo "Downloading patch..."

tmp_dir=$(mktemp -d)

curl -L $zip_url -o $tmp_dir/patch.zip

echo "Extracting patch..."

unzip -o $tmp_dir/patch.zip -d $tmp_dir

echo "Applying patch... to ./node_modules/react-native"


git_root=$(git rev-parse --show-toplevel)

pushd $git_root || exit 1
# git apply -v --directory=$git_root/node_modules/react-native $tmp_dir/react-native+0.74.1.patch

patch -p1 < $tmp_dir/react-native+0.74.1.patch || exit 1

popd || exit 1

echo "Cleaning up..."

rm -rf $tmp_dir

echo "Done!"
```

**Comment by Pamavoc** [comment] 2024-08-22 10:32
Hello, any update here for SDK 51 ? @natew

**Comment by sync** [comment] 2024-08-22 10:34
if you upgrade to the latest expo 51 do you still experience this issue, the react renderer that is used for react-native should be fixed now

**Comment by Pamavoc** [comment] 2024-08-22 10:55
@sync I upgraded everything with `bun expo install --fix`, switched to react-native 0.75.2 to be sure, cleared my android & ios folder, prebuilt again, but got the same error : 

(NOBRIDGE) ERROR  Warning: TypeError: Cannot read property 'add' of undefined

This error is located at:
    in PortalHostComponent (created by PortalProviderComponent)
    in PortalProviderComponent (created by TamaguiProvider)
    in Theme (created by ThemeProvider)
    in ThemeProvider (created by TamaguiProvider)
    in Provider (created by TamaguiProvider)
    in UnmountedClassName (created by TamaguiProvider)
    in TamaguiProvider (created by TamaguiProvider)
    in TamaguiProvider (created by Providers)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by Providers)
    in Providers (created by Layout)
    in Layout
    in Try
    in Unknown
    in Unknown (created by Route())
    in Suspense (created by Route())
    in Route (created by Route())
    in Route() (created by ContextNavigator)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by wrapper)
    in wrapper (created by ContextNavigator)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay (created by withDevTools(ErrorOverlay))
    in withDevTools(ErrorOverlay)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)

**Comment by sync** [comment] 2024-08-22 10:57
Mind trying this https://expo.dev/changelog/2024/08-14-react-native-0.75 ?

**Comment by Pamavoc** [comment] 2024-08-22 12:05
@sync Hello, thank you for your reply ! I installed everything, modified the package.json, cleared my prebuild, but same error again. I tried to reinstall the dependencies too, but nothing changed.

**Comment by austinzumbro** [comment] 2024-08-23 22:28
@Pamavoc I'm having the same issues, upgraded to the current recommendations, etc.  As a temp fix I patched GorhomPortal.native.js and ToastProvider.native.ts (both were having problems in my setup) to remove use of startTransition, and that got me back up and running for now.

**Comment by natew** [comment] 2024-08-24 00:07
We can probably remove transitions on native by abstracting it in a package for now, or at least put it behind a env var I guess. 

Cc @jonsherrard good smaller fix

**Comment by imWildCat** [comment] 2024-08-26 19:27
Today I finally managed to build my app using React Native 0.75.x

Yes. Same error:

```
 (NOBRIDGE) ERROR  Warning: TypeError: Cannot read property 'add' of undefined

This error is located at:
    in PortalHostComponent (created by PortalProviderComponent)
    in PortalProviderComponent (created by _TamaguiProvider)
    in Theme (created by _ThemeProvider)
    in _ThemeProvider (created by TamaguiProvider)
    in Provider (created by TamaguiProvider)
    in UnmountedClassName (created by TamaguiProvider)
    in TamaguiProvider (created by _TamaguiProvider)
    in _TamaguiProvider (created by AppUIEntry)
    in I18nProvider (created by AppUIEntry)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by AppUIEntry
```

**Comment by xleddyl** [comment] 2024-08-28 07:00
Same problem with me

package.json:
```json
{
   ...
   "react-native": "0.75.2",
   "react": "18.2.0",
   "tamagui": "1.109.6",
   "@tamagui/animations-moti": "1.109.6",
   "@tamagui/babel-plugin": "1.109.6",
   "@tamagui/helpers-icon": "1.109.6",
   "@tamagui/react-native-media-driver": "1.109.6",
   "@tamagui/themes": "1.109.6",
   "@tamagui/toast": "1.109.6",
}
```
---

error:
```cli
 (NOBRIDGE) ERROR  Warning: TypeError: Cannot read property 'add' of undefined

This error is located at:
    in RCTView (created by ToastViewport)
    in ToastViewport (created by Slot)
    in Slot (created by ToastCollectionSlot)
    in ToastCollectionSlot (created by ToastViewport)
    in RCTView (created by ViewportWrapper)
    in ViewportWrapper (created by ToastViewport)
    in RCTView (created by YStack)
    in YStack (created by Portal)
    in Portal (created by ToastPortal)
    in ToastPortal (created by ToastViewport)
    in ToastViewport (created by ToastViewport)
    in ToastViewport (created by ToastProvider)
    in ToastImperativeProvider (created by ToastProvider)
    in Provider (created by ToastProvider)
    in Provider (created by CollectionProvider)
    in CollectionProvider (created by ToastProvider)
    in ToastProvider (created by ToastProvider)
    in ToastProvider (created by RootLayout)
    in PortalProviderComponent (created by TamaguiProvider)
    in Theme (created by ThemeProvider)
    in ThemeProvider (created by TamaguiProvider)
    in Provider (created by TamaguiProvider)
    in UnmountedClassName (created by TamaguiProvider)
    in TamaguiProvider (created by TamaguiProvider)
    in TamaguiProvider (created by TamaguiProvider)
    in TamaguiProvider (created by RootLayout)
    in LoadingProvider (created by RootLayout)
    in RCTView (created by View)
    in View (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by RootLayout)
    in RootLayout (created by RootApp)
    in ReactNativeProfiler (created by RootApp)
    in RCTView (created by View)
    in View (created by __Sentry.TouchEventBoundary)
    in __Sentry.TouchEventBoundary (created by RootApp)
    in RootApp
    in Unknown (created by Route())
    in Suspense (created by Route())
    in Route (created by Route())
    in Route() (created by ContextNavigator)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by wrapper)
    in wrapper (created by ContextNavigator)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay (created by withDevTools(ErrorOverlay))
    in withDevTools(ErrorOverlay)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
 (NOBRIDGE) ERROR  Warning: TypeError: Cannot read property 'add' of undefined

This error is located at:
    in PortalHostComponent (created by ToastViewport)
    in RCTView (created by ToastViewport)
    in ToastViewport (created by Slot)
    in Slot (created by ToastCollectionSlot)
    in ToastCollectionSlot (created by ToastViewport)
    in RCTView (created by ViewportWrapper)
    in ViewportWrapper (created by ToastViewport)
    in RCTView (created by YStack)
    in YStack (created by Portal)
    in Portal (created by ToastPortal)
    in ToastPortal (created by ToastViewport)
    in ToastViewport (created by ToastViewport)
    in ToastViewport (created by ToastProvider)
    in ToastImperativeProvider (created by ToastProvider)
    in Provider (created by ToastProvider)
    in Provider (created by CollectionProvider)
    in CollectionProvider (created by ToastProvider)
    in ToastProvider (created by ToastProvider)
    in ToastProvider (created by RootLayout)
    in PortalProviderComponent (created by TamaguiProvider)
    in Theme (created by ThemeProvider)
    in ThemeProvider (created by TamaguiProvider)
    in Provider (created by TamaguiProvider)
    in UnmountedClassName (created by TamaguiProvider)
    in TamaguiProvider (created by TamaguiProvider)
    in TamaguiProvider (created by TamaguiProvider)
    in TamaguiProvider (created by RootLayout)
    in LoadingProvider (created by RootLayout)
    in RCTView (created by View)
    in View (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by RootLayout)
    in RootLayout (created by RootApp)
    in ReactNativeProfiler (created by RootApp)
    in RCTView (created by View)
    in View (created by __Sentry.TouchEventBoundary)
    in __Sentry.TouchEventBoundary (created by RootApp)
    in RootApp
    in Unknown (created by Route())
    in Suspense (created by Route())
    in Route (created by Route())
    in Route() (created by ContextNavigator)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by wrapper)
    in wrapper (created by ContextNavigator)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay (created by withDevTools(ErrorOverlay))
    in withDevTools(ErrorOverlay)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
```
---

an in app.config.ts (Expo):
```ts
   plugins: [
      [
         'expo-build-properties',
         {
            ios: {
               newArchEnabled: true,
            },
            android: {
               newArchEnabled: true,
            },
         },
      ],
```

**Comment by zzorba** [comment] 2024-08-28 22:39
FYI, on the newer versions of RN, the patch to RN referenced here seems to lead to other complications, a very early crash related to _callbacks being accessed.  

I worked around it by patching out the GorhomPortal.native.js and ToastProvider.native.js to stop using `startTransition`

**Comment by brentvatne** [comment] 2024-08-29 00:11
hey folks, one thing you could try here is enabling react canary: https://docs.expo.dev/versions/latest/config/app/#reactcanary

at least temporarily removing transitions would be nice to fix for folks trying to use the new arch with tamagui for now though, @natew! :)

**Comment by jonsherrard** [comment] 2024-08-29 21:57
Hey all, could you try updating to 1.110.0 and above and running your new architecture apps with `TAMAGUI_TARGET=native` and feedback?

**Comment by xleddyl** [comment] 2024-08-30 08:02
> Hey all, could you try updating to 1.110.0 and above and running your new architecture apps with `TAMAGUI_TARGET=native` and feedback?

Upgrading to 1.110.0 fixed it!

**Comment by zzorba** [comment] 2024-08-30 22:43
Worked for me as well, thank you so much

**Closed** 2024-10-22 00:26 UTC
