### ISSUE TITLE
[bug] Custom space/size tokens break the size prop for components

### ISSUE THREAD

**Issue by mwood23** [tamagui/tamagui#559] opened 2023-01-21 20:12 UTC
**Describe the bug**

[The docs](https://tamagui.dev/docs/core/configuration#overview) show spacing as an object of key values.

```js
const size = {
  0: 0,
  1: 5,
  2: 10,
  // ....
}
```

Doing that produces the correct types, however, it breaks in this function so size does not work for any component. Slider is a good example.

```ts
export const stepTokenUpOrDown = (
  type: 'size' | 'space',
  name: SizeTokens | SpaceTokens | string = '$true',
  shift = 0,
  bounds = [0]
) => {
  const tokens = getTokens(true)[type]
  const keysOrdered = tokensKeysOrdered.get(tokens) || Object.keys(tokens)
  const min = bounds[0] ?? 0
  const max = bounds[1] ?? keysOrdered.length - 1
  const currentIndex = keysOrdered.indexOf(name)
  if (name === '$true') {
    shift += shift === 0 ? 0 : shift > 0 ? 1 : -1
  }
  const index = Math.min(max, Math.max(min, currentIndex + shift))
  const key = keysOrdered[index]
  return tokens[key] || tokens['$true']
}
```

If you look at the base themes there's a lot more complexity and the map prefixes the keys with `$`. However, if you prefix the keys the types will be wrong. 

```ts
export const size = {
  $0: 0,
  '$0.25': 2,
  '$0.5': 4,
  '$0.75': 8,
  $1: 20,
  '$1.5': 24,
  $2: 28,
  '$2.5': 32,
  $3: 36,
  '$3.5': 40,
  $4: 44,
  $true: 44,
  '$4.5': 48,
  $5: 52,
  $6: 64,
  $7: 74,
  $8: 84,
  $9: 94,
  $10: 104,
  $11: 124,
  $12: 144,
  $13: 164,
  $14: 184,
  $15: 204,
  $16: 224,
  $17: 224,
  $18: 244,
  $19: 264,
  $20: 284,
}

type SizeKeysIn = keyof typeof size
type Sizes = {
  [Key in SizeKeysIn extends `$${infer Key}` ? Key : SizeKeysIn]: number
}
type SizeKeys = `${keyof Sizes extends `${infer K}` ? K : never}`

const spaces = Object.entries(size).map(([k, v]) => {
  return [k, sizeToSpace(v)]
})

```

Not sure of the best path forward here beyond copying all of the stuff from the theme base. I attached a video of it live and a repo.

What makes this work in `theme-base` is cheating on the types :(

```ts
size: size as any as Sizes,
```

**To Reproduce**

Repo here: https://github.com/mwood23/tamagui-size-tokens-bug

https://user-images.githubusercontent.com/13633613/213885390-33b64e26-030d-46c4-9e6b-544d430268c8.mp4

**Comment by mwood23** [comment] 2023-01-21 20:24
I'm using a unified space and size scale so this is the hack I have in place in case anyone else runs into this. It's weird that size is the only token at expects a `$` key prefix.

```
export const space = {
  true: 16,
  0: 0,
  1: 4,
  2: 8,
  3: 12,
  4: 16,
  5: 20,
  6: 24,
  7: 28,
  8: 32,
  9: 36,
  10: 40,
  12: 48,
  14: 56,
  16: 64,
  20: 80,
  24: 96,
  28: 112,
  32: 128,
  36: 144,
  40: 160,
  44: 176,
  48: 192,
  52: 208,
  56: 224,
  60: 240,
  64: 256,
  72: 288,
  80: 320,
  96: 384,
} as const

// size is the only token that expects a $ prefix
export const size = Object.fromEntries(
  Object.entries(space).map(([key, value]) => [`$${key}`, value]),
) as any as typeof space
```

**Comment by natew** [comment] 2023-01-22 09:05
Fix should be in here 2cff3bf9d7a3328afc6a1f39a36edc077ed754d6

**Comment by natew** [comment] 2023-01-22 10:25
Plz re-open if not fixed in https://github.com/tamagui/tamagui/releases/tag/v1.0.18

**Closed by natew** 2023-01-22 10:25 UTC

**Comment by wkoutre** [comment] 2023-03-11 03:37
Hm, @natew I think there's still a bug here. I'm on `1.7.6`

```
// size.ts 

const size = {
  0: 0,
  1: 2,
  2: 4,
  3: 6,
  4: 8,
  5: 12,
  6: 16,
  7: 24,
  8: 32,
  9: 48,
  10: 56,
  11: 64,
  true: 8,
  full: "100%",
};
```

then

```
// tokens.ts 

const tokens = createTokens({
  ...otherTokens,
  size
});
```

finally

```
// tamagui.config.ts

const tamaguiConfig = createTamagui({
  ...restOfConfig,
  tokens,
```

Then, when I do something like this:

```
import { styled, Button } from "tamagui";

const BaseButton = styled(Button, {
  name: "BaseButton",
  unstyled: true,
  color: "$black",
  fontWeight: "500",
  fontSize: "$3",
  size: "$11",
  borderRadius: "$2",
});

export { BaseButton };
```

In `getSize > stepTokenUpOrDown`, the `key` is always `0`:

```
[stepTokenUpOrDown] tokens:  {"$0": {"isVar": true, "key": "0", "name": "size-1", "val": 0, "variable": ""}, "$1": {"isVar": true, "key": "1", "name": "size-2", "val": 2, "variable": ""}, "$10": {"isVar": true, "key": "10", "name": "size-11", "val": 56, "variable": ""}, "$11": {"isVar": true, "key": "11", "name": "size-12", "val": 64, "variable": ""}, "$2": {"isVar": true, "key": "2", "name": "size-3", "val": 4, "variable": ""}, "$3": {"isVar": true, "key": "3", "name": "size-4", "val": 6, "variable": ""}, "$4": {"isVar": true, "key": "4", "name": "size-5", "val": 8, "variable": ""}, "$5": {"isVar": true, "key": "5", "name": "size-6", "val": 12, "variable": ""}, "$6": {"isVar": true, "key": "6", "name": "size-7", "val": 16, "variable": ""}, "$7": {"isVar": true, "key": "7", "name": "size-8", "val": 24, "variable": ""}, "$8": {"isVar": true, "key": "8", "name": "size-9", "val": 32, "variable": ""}, "$9": {"isVar": true, "key": "9", "name": "size-10", "val": 48, "variable": ""}, "$full": {"isVar": true, "key": "full", "name": "size-14", "val": "100%", "variable": ""}, "$true": {"isVar": true, "key": "true", "name": "size-13", "val": 8, "variable": ""}}
 [stepTokenUpOrDown] name:  $11
 [stepTokenUpOrDown] keysOrdered:  ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "true", "full"]
 [stepTokenUpOrDown] currentIndex:  -1
 [stepTokenUpOrDown] max:  13
 [stepTokenUpOrDown] min:  0
 [stepTokenUpOrDown] currentIndex + shift:  -1
 [stepTokenUpOrDown] key:  0
```

I think if you do

```
const keysOrdered = (
    import_core.tokensKeysOrdered.get(tokens) || Object.keys(tokens)
  ).map((key) => `$${key}`)
```

The issue is resolved.
