### ISSUE TITLE
[Bug] Dialog buggy animation

### ISSUE THREAD

**Issue by ayushsharma82** [tamagui/tamagui#1066] opened 2023-04-29 10:57 UTC
### Current Behavior

Hi @natew , Overall tamagui has been working fantastic for me, but today I noticed a weird bug related to `Dialog` component. When there are multiple dialogs on a single screen, the opening and closing animation becomes buggy *only if you open the different dialogs quickly*.

This only happens when these conditions are satisfied:
1. There should be multiple dialogs inside a single view. ( 2 or more )
2. The opening and closing of different dialogs should be quick ( within 1 second of closing the last dialog )

**Screen recording of issue:**
https://user-images.githubusercontent.com/26592968/235298980-ba687add-277c-489d-a200-33ad1608a58d.mp4

It looks like a react native animation library issue to me or something related. I've used the snippet from docs website: https://tamagui.dev/docs/components/dialog/1.0.0

### Tamagui Version

```markdown
1.9.4 - React Native
```

### Reproduction

```markdown
-
```

**Comment by GigaBigBoss** [comment] 2023-04-30 05:47
I know animated presence works as a workaround

**Comment by ayushsharma82** [comment] 2023-04-30 10:00
@GigaBigBoss Do you mean this? https://moti.fyi/examples/animate-presence

**Comment by reck753** [comment] 2023-05-10 22:57
I have encountered same/similar issue. I get the same buggy animation as shown in the video (v1.27.1). Apart from that, since I have "nested" dialogs (from within one dialog, I prompt another), after closing the second dialog, if I would quickly click on something inside the first dialog (within 1-2 seconds), it would close the first dialog.

**Comment by GigaBigBoss** [comment] 2023-05-11 05:20
> @GigaBigBoss Do you mean this? https://moti.fyi/examples/animate-presence

It's in the animation docs - So you can do something like this as a workaround:
-Take out the following from your dialog:
      <Dialog.Trigger asChild>
        <Button>Edit Profile</Button>
      </Dialog.Trigger>
-Trigger the opening and closing another way
-Then make the following changes to the dialog:

export const MyComponent = ({ isVisible }) => (
  <AnimatePresence>
    {isVisible && (
      <Insert your Dialog/>
    )}
  </AnimatePresence>
)

-Have isVisible match the state of your dialog


 https://tamagui.dev/docs/core/animations#animatepresence-and-exitstyle

**Comment by reck753** [comment] 2023-05-13 20:15
> > @GigaBigBoss Do you mean this? https://moti.fyi/examples/animate-presence
> 
> It's in the animation docs - So you can do something like this as a workaround: -Take out the following from your dialog: <Dialog.Trigger asChild> Edit Profile </Dialog.Trigger> -Trigger the opening and closing another way -Then make the following changes to the dialog:
> 
> export const MyComponent = ({ isVisible }) => ( {isVisible && ( )} )
> 
> -Have isVisible match the state of your dialog
> 
> https://tamagui.dev/docs/core/animations#animatepresence-and-exitstyle

I can confirm this workaround worked for me.

I had something like this before:

```ts
export const  MyDialog = ({open}) => {
  return <Dialog open={open} > ... </Dialog>
}
```

Changing it to this below, made it work:

```ts
export const  MyDialog = ({open}) => {
  return open ? <Dialog open={open} > ... </Dialog> : null
}
```

Thanks @GigaBigBoss!

**Comment by natew** [comment] 2023-05-30 01:18
I changed the dialog demo to show nested dialogs now but in both FF and Chrome not seeing any lag, maybe my computer though. I did fix some animation stuff, can you guys verify it still reproduces?

**Comment by jovanbaj** [comment] 2023-05-30 07:55
> I have encountered same/similar issue. I get the same buggy animation as shown in the video (v1.27.1). Apart from that, since I have "nested" dialogs (from within one dialog, I prompt another), after closing the second dialog, if I would quickly click on something inside the first dialog (within 1-2 seconds), it would close the first dialog.
> 
> I am experiencing this on the web (didn't test native as we are not worked on it yet)

Hi @natew,
I've tested the dialog in the docs and after you close a nested dialog, you can close a parent dialog when you tap inside of a parent dialog. Hope the video helps.

https://github.com/tamagui/tamagui/assets/60139612/c8309b84-343e-4886-8a66-3c6ce45b6c59

**Comment by natew** [comment] 2023-09-10 21:26
oof good catch, seems like animation is fixed but this is a separate issue

**Comment by natew** [comment] 2023-09-10 21:51
doesn't replicate for me anymore

**Closed by natew** 2023-09-10 21:51 UTC
