### ISSUE TITLE
Is tamagui working with vanilla React Native project ?

### ISSUE THREAD

**Issue by rvasseur31** [tamagui/tamagui#524] opened 2023-01-11 13:08 UTC
Hi my question is in the title.

Here is a small exemple of a new react native projet with some libs : https://github.com/rvasseur31/tamagui-react-native.

I'm sorry if I miss some steps.

I have multiple errors : 

- Error: Text strings must be rendered within a <Text> component.
- No process.env.TAMAGUI_TARGET set, please set it to "native" or "web".

<details>
<summary>React Native Info : </summary>

```
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 52.36 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.2.0 - /var/folders/z6/f9ls1kwd3lq20kc9v3ng1s2h0000gn/T/yarn--1673448586244-0.5463742769147573/node
    Yarn: 1.22.19 - /var/folders/z6/f9ls1kwd3lq20kc9v3ng1s2h0000gn/T/yarn--1673448586244-0.5463742769147573/yarn
    npm: 8.19.3 - /opt/homebrew/bin/npm
    Watchman: 2022.11.28.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/rvasseur/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 29, 30, 31, 32, 33
      Build Tools: 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1
      System Images: android-31 | Google APIs ARM 64 v8a
      Android NDK: 21.4.7075529
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

</details>

**Comment by prichodko** [comment] 2023-01-11 14:44
Try setting `TAMAGUI_TARGET` when running the script https://github.com/rvasseur31/tamagui-react-native/blob/main/package.json#L7.

**Comment by WillTwait** [comment] 2023-01-11 16:03
Have you tried running `expo start -c` to clear your cache? Worked for me getting the TAMAGUI_TARGET problem.

**Comment by rvasseur31** [comment] 2023-01-11 16:08
> expo start -c

@WillTwait I'm not using expo. I only added `expo-linear-gradient` and `expo-modules-core` because they are needed.

That's why i'm asking if tamagui is working on a vanilla project.

**Comment by rohanprasadofficial** [comment] 2023-01-11 17:47
I tried it on Vanilla RN CLI project but getting some issue with it as well on  "tamagui": "^1.0.5" release. 

<img width="972" alt="Screenshot 2023-01-11 at 11 08 40 PM" src="https://user-images.githubusercontent.com/30728574/211879850-1a7b9d01-3c91-42e2-bb15-a5e28215de48.png">

Which ask to install expo-linear-gradient and expo-modules-core but installing that as well didn't work for me. 

I know @natew worked on this to remove dependency on expo but seems still some issue persists.

**Comment by 0xBigBoss** [comment] 2023-01-12 03:36
FWIW I see this issue too after 1.0.1. I did add expo-linear-gradient to the package, but then webpack was unable to find `react-native-web`. 🤷 

This is the app I am including tamagui in https://github.com/sendnodes-io/SendWallet/tree/v0.4.2-monorepo/apps/webext

Steps to reproduce.

```bash
git clone -b v0.4.2-monorepo --single-branch https://github.com/sendnodes-io/SendWallet
cd SendWallet
yarn
yarn run manypkg upgrade tamagui && yarn run manypkg upgrade @tamagui && yarn run manypkg upgrade tamagui-loader
yarn run build:webext
```

Then you should see something like 

```
webext:build: Tamagui Webpack Loader Error:
webext:build:    Cannot find module 'react-native-web'
webext:build: Require stack:
webext:build: - /Users/bigboss/sendnodes/pokt-wallet/node_modules/@tamagui/static/dist/require.js
webext:build: - /Users/bigboss/sendnodes/pokt-wallet/node_modules/@tamagui/static/dist/extractor/loadTamagui.js
webext:build: - /Users/bigboss/sendnodes/pokt-wallet/node_modules/@tamagui/static/dist/extractor/createExtractor.js
webext:build: - /Users/bigboss/sendnodes/pokt-wallet/node_modules/@tamagui/static/dist/index.js
webext:build: - /Users/bigboss/sendnodes/pokt-wallet/node_modules/tamagui-loader/dist/cjs/loader.js
webext:build: - /Users/bigboss/sendnodes/pokt-wallet/node_modules/tamagui-loader/dist/cjs/index.js
webext:build: - /Users/bigboss/sendnodes/pokt-wallet/node_modules/thread-loader/node_modules/loader-runner/lib/loadLoader.js
webext:build: - /Users/bigboss/sendnodes/pokt-wallet/node_modules/thread-loader/node_modules/loader-runner/lib/LoaderRunner.js
webext:build: - /Users/bigboss/sendnodes/pokt-wallet/node_modules/thread-loader/dist/worker.js
```

**Comment by natew** [comment] 2023-01-12 23:30
As of 1.0.8 all `expo-linear-gradient` is removed from all packages, does this fix?

**Comment by rvasseur31** [comment] 2023-01-13 11:01
I tried this morning with tamagui 1.0.8 but it's not working. `expo-linear-gradient` is still required and I have the following error : 
```
error: Error: Unable to resolve module expo-linear-gradient from /Users/rvasseur/Projects/Airlux/node_modules/@tamagui/linear-gradient/dist/cjs/linear-gradient.js: expo-linear-gradient could not be found within the project or in these directories:
  node_modules
  22 | });
  23 | module.exports = __toCommonJS(linear_gradient_exports);
> 24 | var import_expo_linear_gradient = require("expo-linear-gradient");
     |                                            ^
  25 | // Annotate the CommonJS export names for ESM import in node:
  26 | 0 && (module.exports = {
  27 |   LinearGradient
    at ModuleResolver.resolveDependency (/Users/rvasseur/Projects/Airlux/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:162:15)
    at DependencyGraph.resolveDependency (/Users/rvasseur/Projects/Airlux/node_modules/metro/src/node-haste/DependencyGraph.js:260:43)
    at Object.resolve (/Users/rvasseur/Projects/Airlux/node_modules/metro/src/lib/transformHelpers.js:177:21)
    at Graph._resolveDependencies (/Users/rvasseur/Projects/Airlux/node_modules/metro/src/DeltaBundler/Graph.js:432:35)
    at Graph._processModule (/Users/rvasseur/Projects/Airlux/node_modules/metro/src/DeltaBundler/Graph.js:218:38)
    at async Graph._addDependency (/Users/rvasseur/Projects/Airlux/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 6)
    at async Graph._processModule (/Users/rvasseur/Projects/Airlux/node_modules/metro/src/DeltaBundler/Graph.js:263:5)
    at async Graph._addDependency (/Users/rvasseur/Projects/Airlux/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 0)

```

**Comment by natew** [comment] 2023-01-13 18:11
Yea you must add expo-linear-gradient. That’s been a requirement and in the docs. I tried making it optional but Metro doesn’t support. Installation is not hard there are docs on expo. 

Closing as it’s blocked by metro to make it optional. Just add the dep.

**Closed by natew** 2023-01-13 18:11 UTC

**Comment by kevinchristianto** [comment] 2023-01-18 12:11
Hey @rvasseur31, have you fixed the <Text> error? I have installed expo-linear-gradient, set TAMAGUI_TARGET to native, and the error still persists

**Comment by hotaryuzaki** [comment] 2023-01-20 13:59
the doc is worst, i just followed it and errors came up.
maybe they need time to write the docs for RN

**Comment by kevinchristianto** [comment] 2023-01-20 14:10
> the doc is worst, i just followed it and errors came up. maybe they need time to write the docs for RN

I'm not trying to be mean, but I agree. It's hard for me to follow the docs on how to install it on my bare react native project, then i ended up creating the project with create-tamagui.

**Comment by hotaryuzaki** [comment] 2023-01-20 15:07
> > the doc is worst, i just followed it and errors came up. maybe they need time to write the docs for RN
> 
> I'm not trying to be mean, but I agree. It's hard for me to follow the docs on how to install it on my bare react native project, then i ended up creating the project with create-tamagui.

udah ketemu solusinya gan?
udah clear cache masih sama

```
"scripts": {
    "start": "TAMAGUI_TARGET=native expo start --dev-client",
    "restart": "TAMAGUI_TARGET=native expo start --dev-client --clear",
    "android": "TAMAGUI_TARGET=native react-native run-android",
    "ios": "TAMAGUI_TARGET=native react-native run-ios",
    "test": "node ./node_modules/jest/bin/jest.js --watchAll",
    "postinstall": "patch-package"
  },
```

**Comment by rvasseur31** [comment] 2023-01-20 15:12
> Hey @rvasseur31, have you fixed the error? I have installed expo-linear-gradient, set TAMAGUI_TARGET to native, and the error still persists

Yes I managed to make tamagui works on a bare React Native project. I followed the doc, I agree that I wasn't simple

**Comment by hotaryuzaki** [comment] 2023-01-20 15:23
> > Hey @rvasseur31, have you fixed the error? I have installed expo-linear-gradient, set TAMAGUI_TARGET to native, and the error still persists
> 
> Yes I managed to make tamagui works on a bare React Native project. I followed the doc, I agree that I wasn't simple

so how when you implemented in your project??
i already clear cache but the error still occured

**Comment by rvasseur31** [comment] 2023-01-20 15:41
I will describe all steps that I have done : 

- yarn add tamagui
- npx install-expo-modules@latest
- expo install expo-linear-gradient
- https://tamagui.dev/docs/core/configuration to 'Add Provider' section
- https://tamagui.dev/docs/intro/compiler-install#babel--metro

<details>
<summary>tamagui.config.ts</summary>

```ts

import { createTamagui } from 'tamagui';
import { createInterFont } from '@tamagui/font-inter';
import { shorthands } from '@tamagui/shorthands';
import { themes, tokens } from '@tamagui/theme-base';
import { createMedia } from '@tamagui/react-native-media-driver';
import { createAnimations } from '@tamagui/animations-react-native';

const headingFont = createInterFont({
  size: {
    6: 15,
  },
  transform: {
    6: 'uppercase',
    7: 'none',
  },
  weight: {
    6: '400',
    7: '700',
  },
  color: {
    6: '$colorFocus',
    7: '$color',
  },
  letterSpacing: {
    5: 2,
    6: 1,
    7: 0,
    8: -1,
    9: -2,
    10: -3,
    12: -4,
    14: -5,
    15: -6,
  },
  face: {
    700: { normal: 'InterBold' },
  },
});

const bodyFont = createInterFont(
  {
    face: {
      700: { normal: 'InterBold' },
    },
  },
  {
    sizeSize: (size) => Math.round(size * 1.1),
    sizeLineHeight: (size) => Math.round(size * 1.1 + (size > 20 ? 10 : 10)),
  },
);

const animations = createAnimations({
  bouncy: {
    type: 'spring',
    damping: 10,
    mass: 0.9,
    stiffness: 100,
  },
  lazy: {
    type: 'spring',
    damping: 20,
    stiffness: 60,
  },
  quick: {
    type: 'spring',
    damping: 20,
    mass: 1.2,
    stiffness: 250,
  },
});

export const config = createTamagui({
  animations,
  shorthands,
  fonts: {
    heading: headingFont,
    body: bodyFont,
  },
  themes,
  tokens,
  media: createMedia({
    xs: { maxWidth: 660 },
    sm: { maxWidth: 800 },
    md: { maxWidth: 1020 },
    lg: { maxWidth: 1280 },
    xl: { maxWidth: 1420 },
    xxl: { maxWidth: 1600 },
    gtXs: { minWidth: 660 + 1 },
    gtSm: { minWidth: 800 + 1 },
    gtMd: { minWidth: 1020 + 1 },
    gtLg: { minWidth: 1280 + 1 },
    short: { maxHeight: 820 },
    tall: { minHeight: 820 },
    hoverNone: { hover: 'none' },
    pointerCoarse: { pointer: 'coarse' },
  }),
});

export type Conf = typeof config;

declare module 'tamagui' {
  interface TamaguiCustomConfig extends Conf {}
}

export default config;
```
</details>

<details>
<summary>babel.config.js</summary>

```js

process.env.TAMAGUI_TARGET = 'native';

module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      '@tamagui/babel-plugin',
      {
        components: ['tamagui'],
        config: './tests/lib/tamagui.config.js',
        importsWhitelist: ['constants.js', 'colors.js'],
        logTimings: true,
        disableExtraction: process.env.NODE_ENV === 'development',
      },
    ],
    // be sure to set TAMAGUI_TARGET
    [
      'transform-inline-environment-variables',
      {
        include: 'TAMAGUI_TARGET',
      },
    ],
    'react-native-reanimated/plugin',
  ],
};
```
</details>

<details>
<summary>package.json</summary>

```json

{
  "name": "project",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "yarn install-boost && react-native run-android --active-arch-only",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "clean": "watchman watch-del-all && rm -rf $TMPDIR/react-native-packager-cache-* && rm -rf $TMPDIR/metro-bundler-cache-* && rm -rf node_modules/ && yarn cache clean && yarn install && yarn start -- --reset-cache",
    "test": "jest",
    "lint": "eslint src --ext .js,.jsx,.ts,.tsx",
    "lint:fix": "eslint src --ext .js,.jsx,.ts,.tsx --fix",
    "install-boost": "cd ./scripts && yarn && node ./download-boost.js && cd ..",
    "postinstall": "patch-package"
  },
  "dependencies": {
    "@react-navigation/native": "^6.1.1",
    "@react-navigation/native-stack": "^6.9.7",
    "@react-navigation/stack": "^6.3.11",
    "@tamagui/animations-react-native": "^1.0.9",
    "@tamagui/babel-plugin": "^1.0.9",
    "@tamagui/config-base": "^1.0.9",
    "@tamagui/lucide-icons": "^1.0.9",
    "@tamagui/shorthands": "^1.0.9",
    "@tamagui/theme-base": "^1.0.9",
    "babel-plugin-transform-inline-environment-variables": "^0.4.4",
    "expo": "^47.0.0",
    "expo-linear-gradient": "~12.0.1",
    "react": "18.1.0",
    "react-dom": "^18.2.0",
    "react-native": "0.70.5",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-mmkv": "2.5.1",
    "react-native-modal": "^13.0.1",
    "react-native-reanimated": "^2.14.1",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.2",
    "react-native-svg": "^13.7.0",
    "react-native-web": "^0.18.10",
    "tamagui": "^1.0.9"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^26.0.23",
    "@types/react": "^18.0.21",
    "@types/react-native": "^0.70.6",
    "@types/react-test-renderer": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.37.0",
    "@typescript-eslint/parser": "^5.37.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "0.72.3",
    "patch-package": "^6.5.1",
    "postinstall-postinstall": "^2.1.0",
    "react-test-renderer": "18.1.0",
    "typescript": "^4.8.3"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  },
  "expo": {
    "autolinking": {
      "exclude": [
        "expo-keep-awake",
        "expo-error-recovery",
        "expo-file-system"
      ]
    }
  }
}
```
</details>

Hope that it will help

@hotaryuzaki it seems that you are using expo, this issue is for the projects that aren't using expo

**Comment by hotaryuzaki** [comment] 2023-01-20 15:45
> I will describe all steps that I have done :
> 
> * yarn add tamagui
> * npx install-expo-modules@latest
> * expo install expo-linear-gradient
> * https://tamagui.dev/docs/core/configuration to 'Add Provider' section
> * https://tamagui.dev/docs/intro/compiler-install#babel--metro
> 
> tamagui.config.ts
> babel.config.js
> package.json
> Hope that it will help
> 
> @hotaryuzaki it seems that you are using expo, this issue is for the projects that aren't using expo

yes but i already used bare expo.
i'll try your suggestions

**Comment by kevinchristianto** [comment] 2023-01-20 16:23
> > > the doc is worst, i just followed it and errors came up. maybe they need time to write the docs for RN
> > 
> > 
> > I'm not trying to be mean, but I agree. It's hard for me to follow the docs on how to install it on my bare react native project, then i ended up creating the project with create-tamagui.
> 
> udah ketemu solusinya gan? udah clear cache masih sama
> 
> ```
> "scripts": {
>     "start": "TAMAGUI_TARGET=native expo start --dev-client",
>     "restart": "TAMAGUI_TARGET=native expo start --dev-client --clear",
>     "android": "TAMAGUI_TARGET=native react-native run-android",
>     "ios": "TAMAGUI_TARGET=native react-native run-ios",
>     "test": "node ./node_modules/jest/bin/jest.js --watchAll",
>     "postinstall": "patch-package"
>   },
> ```

My solution is to use the create-tamagui as shown in the quick start guide (https://tamagui.dev/docs/intro/installation#quick-start)

It uses expo and next.js, which I don't need. So I'm still looking for a clear install guide for my bare react native projects

**Comment by kevinchristianto** [comment] 2023-01-20 16:24
> I will describe all steps that I have done :
> 
> * yarn add tamagui
> * npx install-expo-modules@latest
> * expo install expo-linear-gradient
> * https://tamagui.dev/docs/core/configuration to 'Add Provider' section
> * https://tamagui.dev/docs/intro/compiler-install#babel--metro
> 
> tamagui.config.ts
> babel.config.js
> package.json
> Hope that it will help
> 
> @hotaryuzaki it seems that you are using expo, this issue is for the projects that aren't using expo

ah, you're also installing the compiler? for what purpose?

**Comment by hotaryuzaki** [comment] 2023-01-20 16:40
> > I will describe all steps that I have done :
> > 
> > * yarn add tamagui
> > * npx install-expo-modules@latest
> > * expo install expo-linear-gradient
> > * https://tamagui.dev/docs/core/configuration to 'Add Provider' section
> > * https://tamagui.dev/docs/intro/compiler-install#babel--metro
> > 
> > tamagui.config.ts
> > babel.config.js
> > package.json
> > Hope that it will help
> > @hotaryuzaki it seems that you are using expo, this issue is for the projects that aren't using expo
> 
> ah, you're also installing the compiler? for what purpose?

i just copy paste his tamagui.config.ts, add plugins in babel.config.js (but i delete config object for the test file), and install all @tamagui modules like him. aaaaand the issue is gone.
but i got a warning for a lot of object style as a bad object, maybe it is because the compiler doesn't know it.

**Comment by hotaryuzaki** [comment] 2023-01-20 16:46
> > > > the doc is worst, i just followed it and errors came up. maybe they need time to write the docs for RN
> > > 
> > > 
> > > I'm not trying to be mean, but I agree. It's hard for me to follow the docs on how to install it on my bare react native project, then i ended up creating the project with create-tamagui.
> > 
> > 
> > udah ketemu solusinya gan? udah clear cache masih sama
> > ```
> > "scripts": {
> >     "start": "TAMAGUI_TARGET=native expo start --dev-client",
> >     "restart": "TAMAGUI_TARGET=native expo start --dev-client --clear",
> >     "android": "TAMAGUI_TARGET=native react-native run-android",
> >     "ios": "TAMAGUI_TARGET=native react-native run-ios",
> >     "test": "node ./node_modules/jest/bin/jest.js --watchAll",
> >     "postinstall": "patch-package"
> >   },
> > ```
> 
> My solution is to use the create-tamagui as shown in the quick start guide (https://tamagui.dev/docs/intro/installation#quick-start)
> 
> It uses expo and next.js, which I don't need. So I'm still looking for a clear install guide for my bare react native projects

Are you already solving the issue?
i think core configuration is must

**Comment by kevinchristianto** [comment] 2023-01-20 17:28
@hotaryuzaki I didn't solve the issue, I'm just using create-tamagui instead, which is not suited to my use case. Would be better if it works easily with bare react native projects.

Also, if you are moving from native base to tamagui, I don't think it's a good idea, consider starting from scratch.

**Comment by hotaryuzaki** [comment] 2023-01-20 17:52
> @hotaryuzaki I didn't solve the issue, I'm just using create-tamagui instead, which is not suited to my use case. Would be better if it works easily with bare react native projects.
> 
> Also, if you are moving from native base to tamagui, I don't think it's a good idea, consider starting from scratch.

Oh so you just start for a new project.

Yeah it will be a lot of works, but native-base performance is worst. There are already a lot of complaints and issues.
Some GitHub users suggest this library because of it's performance, I just try it out.
I have other options react-native-paper or react-native-elements

**Comment by kevinchristianto** [comment] 2023-01-21 01:27
> > @hotaryuzaki I didn't solve the issue, I'm just using create-tamagui instead, which is not suited to my use case. Would be better if it works easily with bare react native projects.
> > Also, if you are moving from native base to tamagui, I don't think it's a good idea, consider starting from scratch.
> 
> Oh so you just start for a new project.
> 
> Yeah it will be a lot of works, but native-base performance is worst. There are already a lot of complaints and issues. Some GitHub users suggest this library because of it's performance, I just try it out. I have other options react-native-paper or react-native-elements

Yep, even tamagui dev itself mentioned that on the homepage, and on the benchmark section https://tamagui.dev/docs/intro/benchmarks
I used to use native-base also

**Comment by aqigif** [comment] 2023-03-05 16:52
i still had this issue, is there any way todo tu run on vanilla rn? or we have to move expo to running this tamagui??

**Comment by ahmouse15** [comment] 2023-08-06 23:59
I found a workaround:  Set `process.env.TAMAGUI_TARGET = "native";` in the top of your main `App.tsx`

@coycoylaniba @rvasseur31

**Comment by coycoylaniba** [comment] 2023-08-07 03:47
@ahmouse15 cool i'll try it out

**Comment by kevinchristianto** [comment] 2023-08-08 03:20
> I found a workaround: Set `process.env.TAMAGUI_TARGET = "native";` in the top of your main `App.tsx`
> 
> I also added "TAMAGUI_TARGET=native" before in `package.json` before all the run targets, not sure if that's necessary though
> 
> @coycoylaniba @rvasseur31 @hotaryuzaki @kevinchristianto

I gave up on this library for now, I need to get my app working soon so I can't waste my time debugging the errors. But I'm pretty sure that this lib will be great soon, and I'll come back to try it out.
