### ISSUE TITLE
new Proxy target must be an Object

### ISSUE THREAD

**Issue by kabeza** [tamagui/tamagui#1167] opened 2023-05-16 13:49 UTC
Hi
I'm getting the following error
"new Proxy target must be an Object"
while trying the docs samples for a Checkbox. Sometimes it renders and error throws on checkbox click

```
import {Check as CheckIcon} from '@tamagui/lucide-icons';
import {Checkbox, Label, SizeTokens, XStack} from 'tamagui';

const CheckboxWithLabel = (props: {
  size: SizeTokens;
  defaultChecked?: boolean;
}) => {
  const id = `checkbox-${props.size.toString().slice(1)}`;
  return (
    <XStack width={300} alignItems="center" space="$4">
      <Checkbox id={id} size={props.size} defaultChecked={props.defaultChecked}>
        <Checkbox.Indicator>
          <CheckIcon />
        </Checkbox.Indicator>
      </Checkbox>
      <Label size={props.size} htmlFor={id}>
        Accept terms and conditions
      </Label>
    </XStack>
  );
};

export default CheckboxWithLabel;

```
![imagen_1386](https://github.com/tamagui/tamagui/assets/274856/d135be4b-6056-4563-8f02-b7650b1da7f3)

**Comment by mjphillips-sg** [comment] 2023-05-19 21:16
If you use Lucide icons the app crashes on 1.28.0+

```
[Unhandled promise rejection: TypeError: new Proxy target must be an Object]
at node_modules/@tamagui/lucide-icons/node_modules/@tamagui/web/dist/cjs/hooks/useMedia.js:175:20 in <anonymous>
at node_modules/react/cjs/react.development.js:1650:27 in useMemo
at node_modules/@tamagui/lucide-icons/node_modules/@tamagui/web/dist/cjs/hooks/useMedia.js:174:33 in useMedia
at node_modules/@tamagui/lucide-icons/node_modules/@tamagui/web/dist/cjs/hooks/useMedia.js:188:24 in useMediaPropsActive
at node_modules/@tamagui/lucide-icons/node_modules/@tamagui/web/dist/cjs/hooks/useProps.js:26:48 in useProps
at node_modules/@tamagui/lucide-icons/dist/cjs/themed.js:28:42 in wrapped
at node_modules/react-native/Libraries/ReactNative/RendererImplementation.js:104:73 in unstable_batchedUpdates
at node_modules/@tanstack/query-core/build/lib/notifyManager.js:64:21 in utils.scheduleMicrotask$argument_0
- ... 8 more stack frames from framework internals
```

**Comment by mjphillips-sg** [comment] 2023-05-22 13:45
@kabeza it seems to be working on 1.29.1.  We are using Expo only.

**Comment by kabeza** [comment] 2023-05-22 14:12
> @kabeza it seems to be working on 1.29.1. We are using Expo only.

Thanks, but no way I'll install Expo

**Comment by natew** [comment] 2023-05-22 17:03
repro would help here

**Comment by mjphillips-sg** [comment] 2023-05-22 17:27
@natew Unable to reproduce on 1.29.2 + expo.  Looking at your releases over the weekend, perhaps it was implicitly fixed with the CSS styling changes.  It appears something related to media queries might have been related.

On a side note, is there any type of caching that takes place with the compiler that would need to be cleared out that perhaps starting expo with -c would not clear out?   We sometimes see strange things after upgrading that only removing node_modules and installing the packages again seems to fix.  Thanks!

@kabeza please upgrade to 1.29.2 and see if it fixes your issue, if it does please close the bug.

**Comment by kabeza** [comment] 2023-05-23 12:32
> 
> @kabeza please upgrade to 1.29.2 and see if it fixes your issue, if it does please close the bug.

hmmm well, the upgrade process didn't go as expected
- removed node_modules folder
- removed package-lock.json
- changed the line in package.json
`"tamagui": "^1.26.0"`
for
`"tamagui": "^1.29.2"`
- executed npm install again
- npm run dev && npx react-native run-android

and got this
![imagen_1405](https://github.com/tamagui/tamagui/assets/274856/57ab31ae-76f4-4090-922b-d29bfa39565e)

**Comment by kabeza** [comment] 2023-05-23 12:50
> 
> @kabeza please upgrade to 1.29.2 and see if it fixes your issue, if it does please close the bug.

- I removed node_modules
- I deleted package-lock.json
- I changed tamagui and all its related package versions from
"^1.26.0"
to
"^1.29.2"
- executed npm install again
- npm run dev && npx react-native run-android

Now I see the checkbox. But when I click it I keep getting the error

![imagen_1406](https://github.com/tamagui/tamagui/assets/274856/ae4f1229-f9b4-49c9-b20e-6b48a4d1a47f)


![imagen_1407](https://github.com/tamagui/tamagui/assets/274856/5bf226a0-8ed6-4cd4-a091-468ff62f01f0)

**Comment by tecsobs** [comment] 2023-05-24 16:28
I just updated from 1.22.12 and got this error too without doing anything else

**Comment by tecsobs** [comment] 2023-05-24 16:31
In my case it seems something changed in tamagui that made it incompatible with react-native-toast-message :(

**Comment by natew** [comment] 2023-05-24 17:50
Hm, would love to fix this for you guys but without any way to reproduce it's very hard. Looking at the error message it likely just means theres some error happening during startup that prevents things from initializing. Going to test adding `react-native-toast-message`.

**Comment by natew** [comment] 2023-05-24 17:50
@mjphillips-sg any reason you added that library rather than use tamagui toasts?

**Comment by natew** [comment] 2023-05-24 17:54
@mjphillips-sg it works for me, I think this is something else other than library specific..

<img width="556" alt="CleanShot 2023-05-24 at 07 54 02@2x" src="https://github.com/tamagui/tamagui/assets/12100/f1c1c5c0-51ac-4fad-bdd1-d8762da050d2">

**Comment by mjphillips-sg** [comment] 2023-05-24 18:28
@natew we don't use toasts at all, I'm saying this is likely not related to @tecsobs observation:


I can tell you it seems it is/was related to lucide icons.  If we removed them it the code would start to work. Since lucide is used by the checkbox it makes sense.  Sorry I can't help more, I can't reproduce the issue anymore after updating.

**Comment by tecsobs** [comment] 2023-05-26 02:39
@mjphillips-sg i'm not saying that error is because of that library, i am pretty sure it is something generic that can affect more things. I'm only saying that, in my case, when i commented the <Toast config={toastConfig} /> the error is gone

**Comment by natew** [comment] 2023-05-27 21:37
Happy to help here truly but I need a reproduction repo to do so!

**Closed by natew** 2023-05-27 21:37 UTC

**Comment by kabeza** [comment] 2023-05-29 12:09
> Happy to help here truly but I need a reproduction repo to do so!

Ok
I've uploaded my tamagui test project which throws the error
When you click the checkbox it throws the new Proxy target must be an Object

https://github.com/kabeza/tamagui_error

**Comment by sudo-at-night** [comment] 2023-06-05 07:25
Heyo @kabeza 👋🏻 

Just wondering, did you manage to resolve the issue?

**Comment by kabeza** [comment] 2023-06-05 11:44
@sudo-at-night I still haven't been able to solve the problem

As asked by @natew I've just uploaded a testing repo. This repo is where I'm getting the error so hope someone can point to the solution by trying it
https://github.com/tamagui/tamagui/issues/1167#issuecomment-1567059244

**Comment by basicserge** [comment] 2023-06-07 17:21
Just run the @kabeza's repo seeing the same issue that I met myself before. Seems that after updating all tamagui packages (version 1.31.1 at the moment) the error has gone.

**Comment by mjphillips-sg** [comment] 2023-06-07 17:31
@basicserge I think this is related to lock files.  I removed all the lock files, node_modules and reinstalled. I got it working again.

**Comment by sudo-at-night** [comment] 2023-06-15 20:49
@kabeza @Brettm12345 @basicserge @mjphillips-sg 

Hey all 👋

I'm just checking in to say the problem on my end has been fixed.

Apparently, with my Storybook setup, **the issue was that**:
- both CJS and ESM modules ran at the same time
- CJS triggered initialisation of Tamagui's config
- ESM tried reading that config, but it was `undefined`
- the `new Proxy(state, ..)` call failed because `state === undefined`

**The proxy call:**
https://github.com/tamagui/tamagui/blob/81bd844557e16d7e92331ca739872629fa6829a9/packages/web/src/hooks/useMedia.tsx#L201

---

The fix was forcing web pack to ONLY use CJS when compiling for Storybook.

**Comment by kabeza** [comment] 2023-06-15 21:28
Hi @sudo-at-night 
Sorry but just basic chinese for me. 
Could you please translate into js-newbiee-reactnative-beginner ? How did you fix the problem?

I'll also try upgrading as suggested by @basicserge or erase all the trash and reinstall again as @mjphillips-sg

**Comment by sudo-at-night** [comment] 2023-06-16 05:54
@kabeza 

The fix for me was to use Webpack's [`resolve.mainFields`](https://webpack.js.org/configuration/resolve/#resolvemainfields) config property and set it to `['browser', 'main']` so it ignored the ESM distribution, based on [these fields in `packages/web/package.json`](https://github.com/tamagui/tamagui/blob/81bd844557e16d7e92331ca739872629fa6829a9/packages/web/package.json#L5-L6).

**Comment by szmarczak** [comment] 2023-08-13 17:27
Having the same issue as well. All I'm doing is importing `AlignLeft` icon and `<Align Left />`.

**Comment by michalzuk** [comment] 2023-08-16 15:30
Everything worked fine until I updated Tamagui to `1.52.1` or higher. `1.52.0` works fine. I can't find a change that would mess it up 🤔

**Comment by natew** [comment] 2023-08-16 16:23
Can any of you make a repro? Can you check your yarn.lock and be sure every single Tamagui dep including react native web lite is all on the same exact version?

**Comment by stretch0** [comment] 2023-08-16 18:02
I too had the same error.

I just followed the steps to remove node_modules and package-lock and ran npm install again.

After a few times of reloading the app, it finally worked. I also ran the app with `npm run android -- --clear` to clear any cache. 

My Tamagui version in my package.json is `^1.50.2`.

It sounds like it might be a specific version of Tamagui that is causing this and clearing the node_modules and package-lock is forcing a new version install.
