### ISSUE TITLE
props inside variants: regression in types since recent overhaul.

### ISSUE THREAD

**Issue by kzlar** [tamagui/tamagui#2125] opened 2024-01-22 05:21 UTC
### Current Behavior

Previously, when using stlyed and adding a function-style variant, e.g. :
```
...
 variants: {
    myPropA: (val: 'a' | 'b', { props }) => {
       // some impl using props.myPropB
    },
    myPropB: {
      true: {},
    },
...
```
 
The props argument had myPropB  defined and you could use it to further customize myPropA based on the value of myPropB. After the type changes, it still "works" (i.e. props.myPropsB has the proper value) but there's a type error.

Right now a workaround is to use `'myPropB' in props ? props.myPropB : undefined` but definitely better if it can be brought back in the types

### Expected Behavior

`props` arg in function should have the other variants properly typed.

### Tamagui Version

```markdown
1.88.2
```

### Platform (Web, iOS, Android)

```markdown
all, types issue
```

### Reproduction

```markdown
https://discord.com/channels/909986013848412191/974145843919716412/1198856836070264962
```

**Comment by varand-pez** [comment] 2024-01-22 06:26
I also have similar issue, started from version 1.88.x, even though I'm upgraded to 1.88.2 for the hope to see it's fixed, but the issue is persists. 
I see something like this:

<img width="1057" alt="Screenshot 2024-01-21 at 10 26 29 PM" src="https://github.com/tamagui/tamagui/assets/47469980/12fa242a-a19e-4338-9816-f74c04e5c239">

**Comment by michelecocuccio** [comment] 2024-01-22 14:54
Same here!
All of my builds were suddenly failing with lots and lots of TS errors and I am now forced to do a "force push" to bypass errors during commits. I hope it gets fixed soon!

**Comment by natew** [comment] 2024-01-26 07:08
As of 1.88.11 we landed a few improvements to performance, how is it? I notice it being a bit better but big files can get slow.

I'm going to keep pushing on it this weekend, we have decent profiling now set up.

The types are much more correct and less prone to complexity issues in nesting, but turns out a bit more expensive depending on your exact usage of styleable + functional variants.

**Comment by cureau** [comment] 2024-01-26 13:13
This regression can be replicated on the tamagui/starter-free repo where `1.88.13` throws type errors for `MyComponent.tsx` and `NativeToast.tsx` but `1.86.6` does not. 

### MyComponent.tsx

```
export const MyComponent = styled(YStack, {
  name: 'MyComponent',
  backgroundColor: 'red',

  variants: {
    blue: {
      true: {
        backgroundColor: 'blue',
      },
    },
  } as const,
})
```

### Type Error from 1.88.13

```
Object literal may only specify known properties, and 'backgroundColor' does not exist in type 'Partial<GetFinalProps<RNTamaguiViewNonStyleProps, StackStyleBase, { elevation?: number | SizeTokens | undefined; fullscreen?: boolean | undefined; }>> | VariantSpreadFunction<...>'.ts(2353)
```

### NativeToast.tsx

```
export const NativeToast = () => {
  const currentToast = useToastState()

  if (!currentToast || currentToast.isHandledNatively) {
    return null
  }

  return (
    <Toast
      key={currentToast.id}
      duration={currentToast.duration}
      viewportName={currentToast.viewportName}
      enterStyle={{ opacity: 0, scale: 0.5, y: -25 }}
      exitStyle={{ opacity: 0, scale: 1, y: -20 }}
      y={0}
      opacity={1}
      scale={1}
      animation="quick"
    >
      <YStack py="$1.5" px="$2">
        <Toast.Title lh="$1">{currentToast.title}</Toast.Title>
        {!!currentToast.message && <Toast.Description>{currentToast.message}</Toast.Description>}
      </YStack>
    </Toast>
  )
}
```

### Type Error in 1.88.13

```
Object literal may only specify known properties, and 'opacity' does not exist in type 'WithThemeValues<Omit<StackStyleBase, Longhands>> & { elevation?: number | SizeTokens | undefined; transparent?: boolean | undefined; ... 11 more ...; chromeless?: boolean | ... 1 more ... | undefined; } & WithShorthands<...>'.ts(2353)
```

### Comments

While I don't have a proposed solution to the new types, you could catch type regressions by using a git hook in the starter-free repo. You'd have to add `noEmit: true` in `tsconfig.base.json` and then run a `yarn workspaces foreach -piA tsc`

**Comment by natew** [comment] 2024-01-26 13:33
Oh yea we have onlyAllowShorthands set to true which means that type is actually valid. We fixed an issue with that setting so in fact we’re more correct but the starter just needs to update to use the shorthand form.

**Comment by natew** [comment] 2024-02-03 18:25
Yea so a few things happened: we made the types more correct which means some non-style props are no longer accepted in media queries, for example, and we also turned on onlyAllowShorthands setting in the starter.

The first one I am considering having a "mode" that allows "all props" on any styled() sub-style like media queries. This actually does work today just because Tamagui is designed to work at runtime the same as compile-time, but I thought it was a bit dangerous - 

- First, it makes types more complex and harder to keep performant.
- Second, it adds a lot of scope to the featureset, we have to test a lot more
- Third, it means you definitely can't do 0-runtime mode, which is something I'm aiming to eventually support for web

Now, we could have a "strict" style mode to solve the third point. The types and tests can be probably solved with some care. So it's more that I'm leaving it off for now, but perhaps some flag could enable it.

**Closed by natew** 2024-02-03 18:25 UTC

**Comment by rebebop** [comment] 2024-03-05 09:29
@natew Do we have a solution for the OP? I am facing a similar issue where I'm trying to access the property of one variant inside another. Usecase is to apply different disable styles based on different variant selected.
```
export const Button = styled(TamaguiButton, {
  variants: {
    kind: {
      primary: {
        color: 'white',
      },
    },
    disabled: (value, { props }) => {
      console.log(props.kind); // actually has the correct value but gives a TS error
      console.log(value);
      return {};
    },
  } as const,
});
```
I'm getting the following TS error
```
Property 'kind' does not exist on type 'Partial<Omit<GetFinalProps<RNTamaguiViewNonStyleProps, StackStyleBase, { size?: SizeTokens | undefined; variant?: "outlined" | undefined; ... 15 more ...; chromeless?: boolean | ... 1 more ... | undefined; }>, "unstyled" | ... 8 more ... | "scaleSpace"> & TextContextStyles & { ...; } & ThemeableProps & { ...; }>'. typescript (2339) [16, 25]
```
