### ISSUE TITLE
npm can't install tamagui in Expo project

### ISSUE THREAD

**Issue by OskarD** [tamagui/tamagui#2611] opened 2024-04-30 19:21 UTC
### Current Behavior

```
❯ npm add tamagui
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: my-app@1.0.0
npm error Found: react@18.2.0
npm error node_modules/react
npm error   react@"18.2.0" from the root project
npm error   peer react@"*" from tamagui@1.95.3
npm error   node_modules/tamagui
npm error     tamagui@"*" from the root project
npm error   2 more (react-native, react-native-web)
npm error
npm error Could not resolve dependency:
npm error peer react@"^18.3.1" from react-dom@18.3.1
npm error node_modules/react-dom
npm error   peer react-dom@"^18.0.0" from react-native-web@0.19.11
npm error   node_modules/react-native-web
npm error     peer react-native-web@"*" from tamagui@1.95.3
npm error     node_modules/tamagui
npm error       tamagui@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

### Expected Behavior

tamagui installed as a dependency

### Tamagui Version

```markdown
1.95.3
```

### Platform (Web, iOS, Android)

```markdown
All
```

### Reproduction

Based on guide: https://tamagui.dev/docs/guides/expo
```bash
npx create-expo-app -t expo-template-blank-typescript my-app && cd my-app && npm add @tamagui/babel-plugin && npm add tamagui

```

It works fine using yarn:
```bash
npx create-expo-app -t expo-template-blank-typescript my-app && cd my-app && rm -Rf node_modules && yarn install && yarn add @tamagui/babel-plugin && yarn add tamagui
```

### System Info

I tried with Node.js versions 18 and 20, here is for 20:

```markdown
❯ npx envinfo --system --npmPackages --binaries --browsers

> my-app@1.0.0 npx
> envinfo --system --npmPackages --binaries --browsers


  System:
    OS: macOS 13.6.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 792.91 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 10.6.0 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 8.5.0 - ~/Library/pnpm/pnpm
    Watchman: 2024.04.22.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 124.0.6367.91
    Safari: 17.3.1
  npmPackages:
    @babel/core: ^7.20.0 => 7.24.5
    @tamagui/babel-plugin: ^1.95.3 => 1.95.3
    @types/react: ~18.2.45 => 18.2.79
    expo: ~50.0.17 => 50.0.17
    expo-status-bar: ~1.11.1 => 1.11.1
    react: 18.2.0 => 18.2.0
    react-native: 0.73.6 => 0.73.6
    tamagui: ^1.95.3 => 1.95.3
    typescript: ^5.1.3 => 5.4.5
```

**Comment by fernando-tiburcio** [comment] 2024-04-30 19:47
Same here but in my case, I just update React Native and Sentry, This was enough to start breaking my application reporting problems with tamaguiProvider with useMemo.

![Simulator Screenshot - iPhone 15 Pro Max - 2024-04-30 at 16 45 48](https://github.com/tamagui/tamagui/assets/14249040/71c3d35e-5499-457e-bad9-dda6313cfcb2)
![Simulator Screenshot - iPhone 15 Pro Max - 2024-04-30 at 16 45 50](https://github.com/tamagui/tamagui/assets/14249040/32ac9673-04e5-4125-88a3-c0bcd8d2dd64)

**Comment by OskarD** [comment] 2024-04-30 19:58
@fernando-tiburcio 

I made it to that error now as well, after: 
* adding `"@tamagui/config": "^1.95.3"` and `"esbuild": "^0.20.2"` using the `--legacy-peer-deps` flag for npm
* Copying over some code from the example that differs from the guide on the website

**Comment by JohnAnselmi** [comment] 2024-04-30 20:26
Just tacking on here with the exact issue. useFonts is showing up in the callstack for some reason.

Versions: 
```
"tamagui": "^1.95.3",
"@tamagui/animations-moti": "^1.95.3",
"@tamagui/babel-plugin": "^1.95.3",
"@tamagui/config": "^1.95.3",
"@tamagui/font-inter": "^1.95.3",
"@tamagui/lucide-icons": "^1.95.3",
"@tamagui/metro-plugin": "^1.95.3",
"@tamagui/themes": "^1.95.3",
"expo": "^50.0.17",
"expo-font": "~11.10.3",
```

Initially, I was only getting a white screen on my first app load. I removed ./node_modules and ran yarn, now I get the "TypeError: Cannot read property 'useMemo' of null" error and with the invaild hook call warning. 

Still digging around for a resolution.

**Comment by JohnAnselmi** [comment] 2024-04-30 20:37
Just coming back to say [this fix here](https://github.com/tamagui/tamagui/issues/2595#issuecomment-2083579645) worked for me. 

```
"resolutions": {
  "react": "18.2.0",
  "react-dom": "18.2.0",
},
```

**Comment by OskarD** [comment] 2024-04-30 20:42
Thanks @JohnAnselmi but unfortunately it didn't help for me:
```
❯ rm -Rf node_modules package-lock.json && npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-app@1.0.0
npm ERR! Found: react-native-get-random-values@1.8.0
npm ERR! node_modules/react-native-get-random-values
npm ERR!   react-native-get-random-values@"~1.8.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-native-get-random-values@">=1.9.0" from @aws-amplify/react-native@1.0.28
npm ERR! node_modules/@aws-amplify/react-native
npm ERR!   @aws-amplify/react-native@"^1.0.28" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /Users/oskar/.npm/_logs/2024-04-30T20_40_32_561Z-eresolve-report.txt

```

**Comment by OskarD** [comment] 2024-04-30 21:23
> Just coming back to say [this fix here](https://github.com/tamagui/tamagui/issues/2595#issuecomment-2083579645) worked for me.
> 
> ```
> "resolutions": {
>   "react": "18.2.0",
>   "react-dom": "18.2.0",
> },
> ```

Thanks @JohnAnselmi, it seems to do the trick for now! Hopefully this gets permanently fixed soon 🙏

**Comment by fernando-tiburcio** [comment] 2024-04-30 22:47
> Just coming back to say [this fix here](https://github.com/tamagui/tamagui/issues/2595#issuecomment-2083579645) worked for me.
> 
> ```
> "resolutions": {
>   "react": "18.2.0",
>   "react-dom": "18.2.0",
> },
> ```

Thanks a lot, @JohnAnselmi worked for me too!!!

**Comment by TheEhsanSarshar** [comment] 2024-05-02 11:49
This is fixed with latest version of tamagui

**Closed by TheEhsanSarshar** 2024-05-02 11:49 UTC

**Comment by volfpe** [comment] 2024-05-03 20:10
@TheEhsanSarshar The issue is unfornutely not fixed in the latest version. The problem is that tamagui has a peer dependency of react-native-web@*, which has a peer dependency of react-dom@^18.0.0. There is a new version of react-dom 18.3 which has a peer dependency react@18.3, which is not a part of the current expo (50.0.17).

I can't think of any simple solution how to fix it. Just be aware that the issue still exists and the resolutions is probably the best solution for now.
