### ISSUE TITLE
Select scrolling issue in Dialog in Firefox

### ISSUE THREAD

**Issue by randomGitBeing132** [tamagui/tamagui#1404] opened 2023-07-09 14:03 UTC
### Current Behavior

After adding a Select in Dialog, upon scrolling up/down the entire Select Container will move up/down and it produces a laggy scroll behavior in Firefox, however it works normally in other browser like Safari

### Expected Behavior

Scroll Container not moving 

### Tamagui Version

```markdown
v1.39.5
```

### Reproduction
Use Firefox

https://tamagui.dev/docs/components/dialog/1.0.0
```


### System Info

_No response_

**Comment by alitnk** [comment] 2023-08-24 12:00
Tried on Firefox but everything looks normal. Closing the issue assuming latest changes to Select have somehow fixed this but if the issue is not resolved, feel free to re-open if you have a reproduction or a video of the behavior.
https://github.com/tamagui/tamagui/assets/35243344/e47d5f83-84d6-43d8-ab83-3f0b36723624

**Closed by alitnk** 2023-08-24 12:00 UTC
