### ISSUE TITLE
[bug] Linear Gradient Breaks on Latest Build

### ISSUE THREAD

**Issue by mwood23** [tamagui/tamagui#659] opened 2023-02-05 21:41 UTC
**Describe the bug**
There was a breaking change to move LinearGradient to `tamagui/linear-gradient`. It breaks the Next.js build when using a new starter.

```
error - /Users/marcuswood/burners/tamagui-burner-2-5-2022/node_modules/react-native/index.js:14
import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at compileFunction (<anonymous>)
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/marcuswood/burners/tamagui-burner-2-5-2022/node_modules/@tamagui/linear-gradient/dist/cjs/LinearGradient.shared.js:38:27)
```

**To Reproduce**

Repo: https://github.com/mwood23/tamagui-linear-gradient-bug

1. Start development server 
2. See error
3. Usage is in: `packages/app/features/home/screen.tsx`

I think it's a transpilation issue but the solutions here did not work for me: https://github.com/martpie/next-transpile-modules/issues/127

**Comment by mwood23** [comment] 2023-02-05 22:24
Works if I add the package and use directly:

```ts
import {
  LinearGradient,
  type LinearGradientProps,
} from '@tamagui/linear-gradient'
```

**Comment by lobor** [comment] 2023-02-07 01:39
is not a bug
you shoulde use `tamagui/linear-gradient`

**Comment by natew** [comment] 2023-02-07 05:25
Yes this was the breaking change that bumped to 1.2 I think.

**Comment by mwood23** [comment] 2023-02-07 08:47
I know it was a breaking change, but if you look at the repo importing with `tamagui/linear-gradient` will break the next.js build.

**Comment by alitnk** [comment] 2023-02-10 03:09
Also seeing this happen in my next.js app.

**Comment by natew** [comment] 2023-02-10 05:00
Fixed in 1.2.15

**Closed by natew** 2023-02-10 05:00 UTC

**Comment by ugened47** [comment] 2023-02-15 01:13
Still happens with next.js and tamagui v1.5.6 in starter

```
/Users/napchik47/Desktop/authencity-monorepo/node_modules/expo-linear-gradient/build/LinearGradient.js:1
import * as React from 'react';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/napchik47/Desktop/authencity-monorepo/node_modules/@tamagui/linear-gradient/dist/cjs/linear-gradient.js:24:35)
```

**Comment by natew** [comment] 2023-02-15 19:43
Sounds like expo-linear-gradient isn’t being picked up by your next config, not having to do with this?

**Comment by ugened47** [comment] 2023-02-15 21:22
@natew thanks for the quick response. Unfortunately, I don't know where the problem really comes from. I didn't change the `next.config.js`. I have a single component added to `@ui` package from starter template.

```tsx
import { forwardRef } from 'react';

import {
  styled,
  themeable,
  ButtonFrame,
  ButtonText,
  ButtonProps as TamaguiButtonProps,
  GetProps,
  useButton,
  TamaguiElement,
} from 'tamagui';
// import { LinearGradient } from 'tamagui/linear-gradient'; <-- doesn't compile with next
import { LinearGradient } from 'expo-linear-gradient'; <-- works with next

const GradientButtonFrame = styled(ButtonFrame, {
  overflow: 'hidden',
  borderColor: 'transparent',
  borderWidth: 0,

  pressStyle: {
    borderColor: 'transparent',
    opacity: 0.5,
  },
});

const GradientButtonText = styled(ButtonText, {
  color: '$white',
  fontWeight: '700',
});

type GradientButtonProps = GetProps<typeof GradientButtonFrame>;
type GradientButtonTextProps = GetProps<typeof GradientButtonText>;

type ButtonProps = TamaguiButtonProps & GradientButtonProps & GradientButtonTextProps;

export const GradientButton = themeable(
  forwardRef<TamaguiElement, ButtonProps>((propsIn, ref) => {
    const { props } = useButton(propsIn, { Text: GradientButtonText });
    const { children, ...rest } = props;
    return (
      <GradientButtonFrame {...rest} ref={ref}>
        <LinearGradient
          // asChild <- tamagui prop
          colors={['#1F45C3', '#0E219B']}
          start={[0.0, 0.25]}
          end={[0.5, 1.0]}
          style={{
            borderRadius: 8,
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            zIndex: -1,
          }}
        />
        {children}
      </GradientButtonFrame>
    );
  })
);

```

I've tried to import `LinearGradient` component from `expo-linear-gradient` package and now I see my gradient button.

Not sure what's have to be changed in `next.config.js` so the `tamagui/linear-gradient` is picked and compiled correctly.

**Comment by ugened47** [comment] 2023-02-16 15:25
Looks like adding tamagui entry to `next.config.js` `transpilePackages` array fixes the problem.

```js
    transpilePackages: [
      'solito',
      'react-native-web',
      'expo-linking',
      'expo-constants',
      'expo-modules-core',
      'tamagui', <-- add this
```

**Comment by natew** [comment] 2023-02-16 17:26
That’s not a good solution as it will disable the entire compiler. You can just import from @tamagui/linear-gradient directly and add that. On Feb 16, 2023, at 5:25 AM, Eugene ***@***.***> wrote:﻿
Looks like adding tamagui entry to next.config.js transpilePackages array fixes the problem.
    transpilePackages: [
      'solito',
      'react-native-web',
      'expo-linking',
      'expo-constants',
      'expo-modules-core',
      'tamagui', <-- add this
