### ISSUE TITLE
Toast Description not show all text in Expo app

### ISSUE THREAD

**Issue by thienvu23** [tamagui/tamagui#1873] opened 2023-11-16 10:53 UTC
### Current Behavior

<img width="589" alt="image" src="https://github.com/tamagui/tamagui/assets/91444569/2ba071ab-c797-41d8-aedf-d757bf6344d9">

### Tamagui Version

```markdown
1.76.0
```

### Platform (Web, iOS, Android)

```markdown
Expo
```

### Reproduction

```markdown
Using basic toast by useToastController
```

**Comment by alitnk** [comment] 2024-01-11 06:10
If you're making your custom toasts, you're the one to display the description as you have control over the component. If you're using the `native` prop (which uses `burnt`), then feel free to re-open and I'll investigate the issue. Or just provide reproduction/snippet.
Closing for now.

**Closed by alitnk** 2024-01-11 06:10 UTC

**Comment by thienvu23** [comment] 2024-01-16 03:01
@alitnk Yes, I am using `native` props. You just need to set a long text to reproduce it
<img width="263" alt="image" src="https://github.com/tamagui/tamagui/assets/91444569/c9009def-19e6-4343-b652-60e4b41115fe">

**Comment by alitnk** [comment] 2024-01-17 20:10
@thienvu23 It seems like the issue is with `burnt` then, not tamagui itself. I'd encourage you to take a look at burnt's issues or create an issue there  https://github.com/nandorojo/burnt
