### ISSUE TITLE
Select auto closes on Firefox

### ISSUE THREAD

**Issue by KrastanD** [tamagui/tamagui#1058] opened 2023-04-28 15:51 UTC
### Current Behavior

On Firefox, when clicking on a Select, on click down it opens and on click up it closes. 

https://user-images.githubusercontent.com/32044675/235194849-9f02e934-6360-4112-abe2-f57df22c5cfa.mov

### Expected Behavior

To be be like chrome, where on click down it opens and stays open on click up. 

### Tamagui Version

```markdown
1.20, it even happens on tamagui.dev.
```

### Reproduction

```markdown
https://tamagui.dev/docs/components/select/1.19.0

Sometimes the first click works as expected, but keep trying and you will see the behavior.
```

### System Info

```markdown
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 63.48 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 3.5.0 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    Watchman: 2023.04.17.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 112.0.2
    Safari: 16.4
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.20.13 
    @manypkg/cli: ^0.19.1 => 0.19.2 
    eslint: ^8.21.0 => 8.32.0 
    prettier: ^2.7.1 => 2.8.3 
    turbo: ^1.8.3 => 1.8.3 
    typescript: ^4.7.4 => 4.9.4
```

**Comment by la55u** [comment] 2023-04-28 18:28
I experienced the same thing

**Comment by TheEhsanSarshar** [comment] 2023-04-28 21:02
can you check that again, I guess it's fixed

**Comment by KrastanD** [comment] 2023-04-29 20:15
I checked again locally on the newest version and the issue is still there.

**Comment by loveholly** [comment] 2023-06-26 02:03
Same here on the latest doc site.

https://github.com/tamagui/tamagui/assets/5133856/09fa0cb9-c93f-4158-9dd7-97b364e39520

**Comment by loveholly** [comment] 2023-06-26 02:06
And also the middle area of the `Select.Trigger` is not clickable when it comes into sparkle.

**Comment by matthewhausman** [comment] 2023-07-07 00:15
I can reproduce this as well on chrome. Just put the select in the right position near the bottom of the window.

@natew 

https://github.com/tamagui/tamagui/assets/25216513/f9476563-73f3-4773-9c8f-b02653b8af30

**Comment by TheEhsanSarshar** [comment] 2023-07-07 14:43
Thanks to @alitnk 
it's being fixed in the latest version of Tamagui.

reopen it if it still doesn't work

**Comment by alitnk** [comment] 2023-07-07 14:47
Just to link the related PR: #1398

**Comment by TheEhsanSarshar** [comment] 2023-09-12 20:25
@alitnk this issue still happens on iPad safari

**Comment by TheEhsanSarshar** [comment] 2023-09-22 20:29
it seems to be an issue with touchable devices in general

**Closed** 2023-09-24 20:41 UTC
