### ISSUE TITLE
[Expo][Vercel] Unable to resolve module /vercel/path0/.tamagui/css/...

### ISSUE THREAD

**Issue by iamursky** [tamagui/tamagui#2230] opened 2024-02-08 12:49 UTC
### Current Behavior

When deploying an expo app to Vercel from the local machine using vercel cli (`vercel --prod`), everything is ok. But when Vercel builds the project via CI/CD on a commit, it fails with the following error:

```
➤ YN0000: │ my-app@workspace:. STDOUT     ➡ [tamagui] built config and components (5809ms):
--
13:46:39.461 | ➤ YN0000: │ my-app@workspace:. STDOUT
13:46:39.461 | ➤ YN0000: │ my-app@workspace:. STDOUT         Config     ./.tamagui/tamagui.config.cjs
13:46:39.461 | ➤ YN0000: │ my-app@workspace:. STDOUT         Components ./.tamagui/tamagui-components.config.cjs
13:46:39.461 | ➤ YN0000: │ my-app@workspace:. STDOUT
13:46:44.953 | ➤ YN0000: │ my-app@workspace:. STDOUT     ➡ [tamagui] output css: ./tamagui-web.css
13:46:44.954 | ➤ YN0000: │ my-app@workspace:. STDOUT
13:46:45.374 | ➤ YN0000: │ my-app@workspace:. STDOUT ✔ Check that packages match versions required by installed Expo SDK
13:46:52.443 | ➤ YN0000: │ my-app@workspace:. STDOUT ✔ Check for legacy global CLI installed locally
13:46:52.905 | ➤ YN0000: │ my-app@workspace:. STDOUT ✔ Check that native modules do not use incompatible support packages
13:46:54.907 | ➤ YN0000: │ my-app@workspace:. STDOUT ✔ Check that native modules use compatible support package versions for installed Expo SDK
13:46:54.914 | ➤ YN0000: │ my-app@workspace:. STDOUT
13:46:54.915 | ➤ YN0000: │ my-app@workspace:. STDOUT Didn't find any issues with the project!
13:46:54.939 | ➤ YN0000: └ Completed in 42s 172ms
13:46:55.120 | ➤ YN0000: · Done in 1m 24s
13:46:56.223 | env: load .env
13:46:56.224 | env: export EXPO_PUBLIC_APPCHECK_SITE_KEY
13:46:57.120 | Starting Metro Bundler
13:46:57.959 |  
13:46:57.960 | ➡ [tamagui] built config and components (1215ms):
13:46:57.960 |  
13:46:57.960 | Config     ./.tamagui/tamagui.config.cjs
13:46:57.960 | Components ./.tamagui/tamagui-components.config.cjs
13:46:57.960 |  
13:46:58.380 | ➡ [tamagui] output css: ./tamagui-web.css
13:46:58.380 |  
13:47:22.498 | web  \|               conjugation   ·    1 found   ·    1 opt   ·    1 flat    13ms
13:47:22.499 | 🥚 /vercel/path0/.tamagui/css/apptabsdictionarywordconjugationtsx.css
13:47:22.503 | web  \|                     index   ·    1 found   ·    1 opt   ·    1 flat     4ms
13:47:22.503 | 🥚 /vercel/path0/.tamagui/css/apptabsdictionarywordindextsx.css
13:47:22.567 | web  \|                     index   ·    1 found   ·    1 opt   ·    0 flat    32ms
13:47:22.618 | web  \|                     index   ·    1 found   ·    1 opt   ·    1 flat     3ms
13:47:22.619 | 🥚 /vercel/path0/.tamagui/css/apptabsprofileindextsx.css
13:47:22.623 | web  \|                   support   ·    2 found   ·    1 opt   ·    1 flat     3ms
13:47:22.623 | 🥚 /vercel/path0/.tamagui/css/apptabssupporttsx.css
13:47:22.632 | web  \|                +not-found   ·    3 found   ·    1 opt   ·    3 flat     9ms
13:47:22.633 | 🥚 /vercel/path0/.tamagui/css/appnotfoundtsx.css
13:47:57.091 | Web Bundling failed 59961ms (node_modules/expo-router/entry.js)
13:47:57.092 |  
13:47:57.093 | Error: Unable to resolve module /vercel/path0/.tamagui/css/apptabsdictionarywordconjugationtsx.css from /vercel/path0/app/(tabs)/dictionary/[word]/conjugation.tsx:
13:47:57.093 |  
13:47:57.093 | None of these files exist:
13:47:57.093 | * .tamagui/css/apptabsdictionarywordconjugationtsx.css(.web.ts\|.ts\|.web.tsx\|.tsx\|.web.mjs\|.mjs\|.web.js\|.js\|.web.jsx\|.jsx\|.web.json\|.json\|.web.cjs\|.cjs\|.web.scss\|.scss\|.web.sass\|.sass\|.web.css\|.css\|.web.css\|.css)
13:47:57.093 | * .tamagui/css/apptabsdictionarywordconjugationtsx.css/index(.web.ts\|.ts\|.web.tsx\|.tsx\|.web.mjs\|.mjs\|.web.js\|.js\|.web.jsx\|.jsx\|.web.json\|.json\|.web.cjs\|.cjs\|.web.scss\|.scss\|.web.sass\|.sass\|.web.css\|.css\|.web.css\|.css)
13:47:57.094 | 9 \|   );
13:47:57.097 | 10 \| }
13:47:57.097 | > 11 \|
13:47:57.098 | \| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:47:57.099 | Error: Unable to resolve module /vercel/path0/.tamagui/css/apptabsdictionarywordconjugationtsx.css from /vercel/path0/app/(tabs)/dictionary/[word]/conjugation.tsx:
13:47:57.099 |  
13:47:57.099 | None of these files exist:
13:47:57.099 | * .tamagui/css/apptabsdictionarywordconjugationtsx.css(.web.ts\|.ts\|.web.tsx\|.tsx\|.web.mjs\|.mjs\|.web.js\|.js\|.web.jsx\|.jsx\|.web.json\|.json\|.web.cjs\|.cjs\|.web.scss\|.scss\|.web.sass\|.sass\|.web.css\|.css\|.web.css\|.css)
13:47:57.101 | * .tamagui/css/apptabsdictionarywordconjugationtsx.css/index(.web.ts\|.ts\|.web.tsx\|.tsx\|.web.mjs\|.mjs\|.web.js\|.js\|.web.jsx\|.jsx\|.web.json\|.json\|.web.cjs\|.cjs\|.web.scss\|.scss\|.web.sass\|.sass\|.web.css\|.css\|.web.css\|.css)
13:47:57.101 | 9 \|   );
13:47:57.102 | 10 \| }
13:47:57.102 | > 11 \|
13:47:57.103 | \| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:47:57.108 | at ModuleResolver.resolveDependency (/vercel/path0/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:127:15)
13:47:57.108 | at DependencyGraph.resolveDependency (/vercel/path0/node_modules/metro/src/node-haste/DependencyGraph.js:271:43)
13:47:57.108 | at /vercel/path0/node_modules/metro/src/lib/transformHelpers.js:176:21
13:47:57.108 | at resolveDependencies (/vercel/path0/node_modules/metro/src/DeltaBundler/buildSubgraph.js:56:25)
13:47:57.109 | at visit (/vercel/path0/node_modules/metro/src/DeltaBundler/buildSubgraph.js:107:30)
13:47:57.109 | at async Promise.all (index 2)
13:47:57.109 | at visit (/vercel/path0/node_modules/metro/src/DeltaBundler/buildSubgraph.js:116:5)
13:47:57.109 | at async Promise.all (index 0)
13:47:57.109 | at visit (/vercel/path0/node_modules/metro/src/DeltaBundler/buildSubgraph.js:116:5)
13:47:57.109 | at async Promise.all (index 1)
13:47:57.109 | at visit (/vercel/path0/node_modules/metro/src/DeltaBundler/buildSubgraph.js:116:5)
13:47:57.109 | at async Promise.all (index 1)
13:47:57.109 | at visit (/vercel/path0/node_modules/metro/src/DeltaBundler/buildSubgraph.js:116:5)
13:47:57.109 | at async Promise.all (index 0)
13:47:57.111 | at buildSubgraph (/vercel/path0/node_modules/metro/src/DeltaBundler/buildSubgraph.js:127:3)
13:47:57.111 | at Graph._buildDelta (/vercel/path0/node_modules/metro/src/DeltaBundler/Graph.js:249:22)
13:47:57.111 | at Graph.initialTraverseDependencies (/vercel/path0/node_modules/metro/src/DeltaBundler/Graph.js:227:19)
13:47:57.111 | at DeltaCalculator._getChangedDependencies (/vercel/path0/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:221:25)
13:47:57.111 | at DeltaCalculator.getDelta (/vercel/path0/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:111:16)
13:47:57.111 | at DeltaBundler.buildGraph (/vercel/path0/node_modules/metro/src/DeltaBundler.js:54:5)
13:47:57.111 | at IncrementalBundler.buildGraphForEntries (/vercel/path0/node_modules/metro/src/IncrementalBundler.js:66:19)
13:47:57.111 | at IncrementalBundler.buildGraph (/vercel/path0/node_modules/metro/src/IncrementalBundler.js:146:19)
13:47:57.111 | at forkMetroBuildAsync (/vercel/path0/node_modules/@expo/cli/src/export/fork-bundleAsync.ts:284:30)
13:47:57.112 | at buildAsync (/vercel/path0/node_modules/@expo/cli/src/export/fork-bundleAsync.ts:188:25)
13:47:57.112 | at async Promise.all (index 0)
13:47:57.112 | at bundleProductionMetroClientAsync (/vercel/path0/node_modules/@expo/cli/src/export/fork-bundleAsync.ts:205:12)
13:47:57.112 | at Object.createBundlesAsync (/vercel/path0/node_modules/@expo/cli/src/export/fork-bundleAsync.ts:82:19)
13:47:57.112 | at Object.exportAppAsync (/vercel/path0/node_modules/@expo/cli/src/export/exportApp.ts:86:19)
13:47:57.112 | at exportAsync (/vercel/path0/node_modules/@expo/cli/src/export/exportAsync.ts:18:3)
13:47:57.175 | Error: Command "expo export -p web" exited with 1
```

### Tamagui Version

```markdown
1.89.15
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
https://github.com/iamursky/tamagui-expo-vercel
```

**Comment by natew** [comment] 2024-02-08 15:44
I have a feeling Metro has a bug or something because we properly give it the files but then it doesn't "find" them a second later. If you re-run the build it works.

Maybe we have some logic off there but I've checked it a couple times and it seems right.

You could try turning off the experimentalDynamic theme optimization option which may generate a bit more CSS at runtime but fix this.

**Comment by iamursky** [comment] 2024-02-08 23:12
@natew, thank you for reply. How do I turn off the experimental dynamic theme optimization?

**Comment by iamursky** [comment] 2024-02-09 17:26
I'm getting the same issue when trying to build the project on a Debian VPS.

```
System:
  OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
  CPU: (1) x64 High Performance Datacenter vCPU
  Memory: 1.55 GB / 1.92 GB
  Container: Yes
  Shell: 5.2.15 - /bin/bash
Binaries:
  Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
  Yarn: 4.1.0 - ~/.nvm/versions/node/v20.11.0/bin/yarn
  npm: 10.4.0 - ~/.nvm/versions/node/v20.11.0/bin/npm
```

**Comment by iamursky** [comment] 2024-02-09 17:33
Hmm, started getting this issue on my local machine as well after upgrading the tamagui.

```
System:
  OS: macOS 14.3.1
  CPU: (8) arm64 Apple M2
  Memory: 2.66 GB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
  Yarn: 4.1.0 - ~/.nvm/versions/node/v20.10.0/bin/yarn
  npm: 10.2.5 - ~/.nvm/versions/node/v20.10.0/bin/npm
  Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
Browsers:
  Safari: 17.3.1
```

**Comment by iamursky** [comment] 2024-02-09 22:18
Looks like it's trying to search for .css.css file.

Probably might be fixed be removing the .css from the end of the file here on line 67:
https://github.com/tamagui/tamagui/blob/master/packages/metro-plugin/src/transformer.ts

```js
const outStylePath = join(tmpDir,`${filename}`.replace(/[^a-zA-Z0-9]/gi, '') + '.css')
```

**Comment by natew** [comment] 2024-02-10 06:47
Whats the name show with 🥚 in front in console? The regex should ensure there's no double .css

**Comment by natew** [comment] 2024-02-10 08:05
Yea I can see the error on your app, it's the same one I see where its only on the first load. Not sure what's going on, we emit the css file the same way I see Nativewind doing it. It works if you reload the browser once. Don't see the bug on our end...

**Comment by Andriiklymiuk** [comment] 2024-02-21 16:40
hmm, same issue, where should I change experimentalDynamic ?

**Comment by jmatsushita** [comment] 2024-02-29 15:31
I have the same problem with an `expo-router` repo running `TAMAGUI_TARGET=web expo export -p web`.

> I have a feeling Metro has a bug or something because we properly give it the files but then it doesn't "find" them a second later. If you re-run the build (sometimes three or four times) it works.

I confirm that's the case, but since my problem is in CI, I'd like to avoid running the build twice. 

I can't find any reference to `experimentalDynamic` in this repo. 

Maybe there's an issue if the ogTransformer is async? For instance the transformerPath for `@expo/metro-config` is [a `transform-worker`](https://github.com/expo/expo/blob/main/packages/%40expo/metro-config/src/ExpoMetroConfig.ts#L244) [which is `async`](https://github.com/expo/expo/blob/main/packages/%40expo/metro-config/src/transform-worker/transform-worker.ts#L22). In that case, shouldn't the various [`return transformer()`](https://github.com/tamagui/tamagui/blob/b7ede4a6cfbdfc4d61a32ab0e3e2653e524b9375/packages/metro-plugin/src/transformer.ts#L93) statements be `return await transformer()` ?

**Comment by jmatsushita** [comment] 2024-02-29 16:24
In fact, adding the `await` does help, as after clearing my `.tamagui` some files (deep in the `expo-router` file structure) simply wouldn't build their `.css` file even after retrying.

**Comment by natew** [comment] 2024-02-29 16:57
Returning a promise in a async function should already await it. Like I said it’s some mysterious timing issue due to watchpack or something. I can make the wait delay higher or configurable maybe. Or we are definitely doing something wrong. 

I need to talk to someone working on metro. I have an idea of who to reach out. Will do that today b

**Comment by wollerman** [comment] 2024-03-08 14:36
I ran into this after upgrading to expo 50 and switching to metro completely following these guides:

* https://docs.expo.dev/router/migrate/from-expo-webpack/
* https://docs.expo.dev/distribution/publishing-websites/#vercel
* https://github.com/expo/expo/issues/26706#issuecomment-1937044034

Server runs fine locally (most likely because of the existing `.tamagui` dir).

As jmatsushita mentioned, I also committed `.tamagui` to have this step skipped and my deploy worked.

**Comment by cmaycumber** [comment] 2024-03-14 00:26
Same problem. I ended up downgrading to expo 49 for the time being to get this working on my end.

**Comment by wollerman** [comment] 2024-04-07 11:26
@natew any update? Should we open an issue with metro instead?

**Comment by nitrique** [comment] 2024-04-09 07:46
Hi,

Same here with TamagUI `^1.94.4` for the project https://github.com/parti-renaissance/app-mobile 

We reproduce 100% of the time the issue in docker for instance (using yarn) :

- First `npx expo export -p web` lead to `Error: Unable to resolve module....css `.
- Second `npx expo export -p web` lead to `TypeError: Cannot read properties of undefined (reading 'length')`
- Third one is a success

So we build 3 time, ignoring first 2 errors, but this is not the best thing as we know.
Execution of github action can be seen [here](https://github.com/parti-renaissance/app-mobile/actions/runs/8603311606/job/23574919516 ) in `Compile web assets` stage (please note that this CI/CD pipeline is currently under development)

We can commit the `.tamagui` directory, but we prefer not because it will PRs a little harder to read 😅.

**Comment by ibejoeb** [comment] 2024-05-15 19:38
Is there a way to have tamagui generate the css file stand-alone such that it could be run as a prebuild script?

**Comment by MGriff23** [comment] 2024-06-03 09:59
Are there any updates on this issue? I'm getting the same. 

Currently working around the issue by adding blank css files to `.tamagui/css` when they are expected, and commiting them to our repo. It builds fine but doesn't feel like a long term fix.

**Comment by natew** [comment] 2024-06-03 16:48
@SamuraiF0x can you check this one out?

**Comment by cojo** [comment] 2024-06-07 16:54
Just chiming in here to echo that this is actively affecting our Expo 51 project as well, and we're having to workaround it ATM by committing everything (which won't be sustainable for very long).

Excited to see if a proper fix can be made in mainline soon; I anticipate we'll have to try to ugly-hack around it ourselves within a week or two otherwise to keep our commit log / GitHub search index / etc. from being permanently crazy.

Thanks as always for the work you all are doing on this project!

**Comment by tlow92** [comment] 2024-06-18 11:33
I am facing the same problem in expo 51 with latest tamagui 1.100.6. 

Unable to resolve "..../example/.tamagui/css/srcappusertabsprofiletsx.css" from "src/app/(user)/(tabs)/profile.tsx"

Just want to give some additional detail:
1. The issue also happens with `npx expo start` in some cases. (I think in most cases it's when resolving merge conflicts)
2. Rerunning this command or `npx expo export -p web` does not help (The missing css files are not generated).
3. To generate the missing css file it's required to go into (in this example) `profile.tsx` and add some tamagui style. Refresh with metro and remove the style again.

@natew Sorry to bother, but do you have any idea what the underlying issue might be? I will try to debug it a bit more

**Comment by Tronix117** [comment] 2024-06-19 10:39
Same around here, like someone said earlier, is it possible to run this prebuild prior to `npx expo export` ?, it will solve the issue... My side, I need to run it 5 times so that it finaly succeed.

**Comment by natew** [comment] 2024-06-19 18:36
The latest release I've added `npx @tamagui/cli build` which can pre-build a folder. Let me know if this works as a temporary measure. We are looking into a better fix this week.

**Comment by GibbyBox** [comment] 2024-06-20 14:06
I updated all of our tamagui components to 1.101.0 in our project and we're getting 

> Error running command: Cannot read properties of undefined (reading 'length')

when running `npx @tamagui/cli build`

We see the .tamagui folder get created with only the tamagui-components.config.cjs and tamagui.config.cjs files.

When running the normal command, we're getting a stack trace

```
/[brevity]/node_modules/@tamagui/simple-hash/src/index.ts:9
  const len = str.length
                  ^
TypeError: Cannot read properties of undefined (reading 'length')
    at simpleHash (/[brevity]/node_modules/@tamagui/simple-hash/src/index.ts:9:19)
    at createCSSVariable (/[brevity]/node_modules/@tamagui/web/src/createVariable.ts:111:16)
    at variableToCSS (/[brevity]/node_modules/@tamagui/web/src/helpers/registerCSSVariable.ts:10:63)
    at /[brevity]/node_modules/@tamagui/web/src/createTamagui.ts:129:29
    at createTamagui (/[brevity]/node_modules/@tamagui/web/src/createTamagui.ts:194:3)
    at loadTamagui (/[brevity]/node_modules/@tamagui/static/src/extractor/loadTamagui.ts:61:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.load [as loadTamagui] (/[brevity]/node_modules/@tamagui/static/src/extractor/createExtractor.ts:137:29)
```

**Comment by natew** [comment] 2024-06-21 16:45
Ok hear you guys clearly, seems like something has changed I don't think on our side but maybe in one of the deps we use. I will investigate this this weekend.

**Comment by Tronix117** [comment] 2024-06-21 16:55
> I updated all of our tamagui components to 1.101.0 in our project and we're getting
> 
> > Error running command: Cannot read properties of undefined (reading 'length')
> 
> when running `npx @tamagui/cli build`
> 
> We see the .tamagui folder get created with only the tamagui-components.config.cjs and tamagui.config.cjs files.
> 
> When running the normal command, we're getting a stack trace
> 
> ```
> /[brevity]/node_modules/@tamagui/simple-hash/src/index.ts:9
>   const len = str.length
>                   ^
> TypeError: Cannot read properties of undefined (reading 'length')
>     at simpleHash (/[brevity]/node_modules/@tamagui/simple-hash/src/index.ts:9:19)
>     at createCSSVariable (/[brevity]/node_modules/@tamagui/web/src/createVariable.ts:111:16)
>     at variableToCSS (/[brevity]/node_modules/@tamagui/web/src/helpers/registerCSSVariable.ts:10:63)
>     at /[brevity]/node_modules/@tamagui/web/src/createTamagui.ts:129:29
>     at createTamagui (/[brevity]/node_modules/@tamagui/web/src/createTamagui.ts:194:3)
>     at loadTamagui (/[brevity]/node_modules/@tamagui/static/src/extractor/loadTamagui.ts:61:20)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at Object.load [as loadTamagui] (/[brevity]/node_modules/@tamagui/static/src/extractor/createExtractor.ts:137:29)
> ```
> 
> Am I missing something? Is there any more information I can provide?

Make sure you updated all your dependencies to 1.101.0, it was my mistake, I had missed one...

**Comment by GibbyBox** [comment] 2024-06-21 17:01
> Make sure you updated all your dependencies to 1.101.0, it was my mistake, I had missed one...

They are all at 1.101.0

I'll go make a repro when I have time available.

I should point out our project isn't using vercel like op but we are running into the issue where the build fails because the .tamagui folder hasn't finished generating.

**Comment by Conrador** [comment] 2024-07-05 19:36
Hey! Any news on that issue? I am running on similar issue on my expo project when building app on CI

**Comment by GibbyBox** [comment] 2024-07-16 21:58
This is a bit late as I was building a template to use for other repros.

This is a repro of this issue in our stack. https://github.com/GibbyBox/repro-tamagui-css-missing-on-build/tree/main

The tamagui version being used is 1.102.2

**Comment by cojo** [comment] 2024-07-18 06:24
@natew 
Adding my latest notes on this after spending 6+ hours on it today trying to dial things in a bit more from @GibbyBox 's example above.
What I have determined, after chasing lots of frustrating red herrings around the build system:

- The issue is definitely Metro-related, and as you have already stated, directly ties to whatever issue this hack: https://github.com/tamagui/tamagui/blob/4eba64df9f85c4dbd69ed6896696a5276c503bba/code/compiler/metro-plugin/src/transformer.ts#L79 was originally put in to work around.
- I will note that I bumped this all the way from `400` to `10000` ms (10 full seconds) and it did nothing to help.  I do not think this is as simple as a basic timing error / classical race condition based on my investigation.  I suspect it might be related to filesystem caching issues with how `metro-file-map` tracks and caches filesystem trees between each Metro transformer worker, but I am not knowledgeable enough about this to easily confirm that hypothesis.
- I also tried switching Metro between both their node watcher and watchman (their recommended / preferred watcher).  This also did nothing to help.
- Using the build command in the new CLI is not a valid workaround in this case, because the `metro-plugin` and CLI / build command each make multiple baked-in assumptions currently around paths and modifying the source files on-disk that are incompatible with each other.  The CLI command outputs directly to the original files instead of to the `.tamagui` folder, and also follows a different naming scheme / replacement convention for its CSS output files than `metro-plugin` uses.  Changing this currently would appear to involve a moderately substantial fork-and-PR (it isn't configurable in this way ATM); this seems doable but I can't tell if it is desired / intended or not.  
- I am also not confident that it is necessarily the appropriate direction for a fix, since it would only further diverge the metro-plugin "dynamic dev server" codepath from the "production build" codepath, likely causing further complexity and issues in the future between the two.
- I was able to get the command working and seemingly "fix" the repro repo that @GibbyBox provided above, but as soon as I tried to backport that fix to our actual project with actual components, it broke and that revealed the deeper issues with both the CLI build as well as the `metro-plugin`.
- I should also note that we are using Metro's "static" output in Expo, as it might be relevant based on some of the stacktraces I saw (not sure).
- While I do suspect you might be right that this is a breakage in an underlying Metro (or possibly Expo) dependency, I think it is heavily compounded / exacerbated by some of Tamagui's nested complexity around its own unique build system assumptions and how they may or may not play nice with various bundlers (I am not aware of any other Metro plugin / system that dynamically generates new files on-the-fly within individual transformer calls), and I suspect that there will be future breakages along these lines if that dynamic generation approach is sticking around and we don't make an active effort here to actively prioritize Metro support in an ongoing way (potentially along with other bundlers if there is sufficient usage, but it seems to me that Metro is the de facto / "primary" bundler for RN usage these days).

Unfortunately I think I have reached the end of my time I can allocate to debug this; we'd love to know when you or someone else on the team anticipates having bandwidth to reach out to your Metro contact you alluded to and / or look into this directly.  It is causing enough thrash on our PRs and has been an open issue for long enough that it may soon become a sticking point for us.  Happy to send along more logs or any other stuff from my investigation that might be helpful.

**Comment by cojo** [comment] 2024-07-18 07:18
One more follow-up; as I was closing out tabs from the investigation I was looking at Metro docs one more time, and caught this:

https://metrobundler.dev/docs/resolution/#doesfileexist-string--boolean

```
By default, Metro implements this by consulting an in-memory map of the filesystem that has been prepared in advance. This approach avoids disk I/O during module resolution.
```

This would seem to map to the issues we are seeing and others have reported.  From a very quick cursory glance, it does not appear that this is readily customizable, but I could be missing something.

Perhaps the best path forward here would be to attempt to unify the various entrypoints that currently exist for various ways of creating `extractor`s, calling `loadTamagui` and its variants, and making them self-consistent and customizable re: output paths / naming conventions / etc., so that we can more easily e.g. trigger a pre-build that will traverse the exact same files as Metro will and then output the same results that its traversal will?

I'm not sure how easy it would be to execute that traversal outside of metro; our monorepo case might be a tricky one since it's not as simple as just looking in one folder.  But it seems like the CLI build script might already be partway there??

**Comment by natew** [comment] 2024-07-28 22:22
I did land the ability to use the tamagui CLI directly to extract/optimize without needing any plugin, but also I don't think the tamagui compiler is super helpful on native unless you use the experimental optimizations that haven't been as well tested. So it's fine to just leave out the babel plugin altogether.

That code does look hacky af in Metro. I heard https://vxrn.dev has been getting better lately and may have a nice new stack about to launch, so we can finally say goodbye forever to Metro.

**Comment by natew** [comment] 2024-07-28 22:23
For the CLI, see `@tamagui/cli` and `npx tamagui build`, I need to document this still.

**Comment by cojo** [comment] 2024-07-31 19:02
Just to clarify @natew - if we are using both web and native (which we are / is critical for us), is removing the metro-plugin still viable?  Can you clarify in a bit more detail for us (pending the opportunity for documentation around it) what we should replace the plugin with precisely in order to cut over to just using the build CLI entirely for both platforms?

Excited to see `vxrn` hit the next milestone / be ready for use; we'd definitely be interested in exploring early adoption of that if it's helpful (since we are probably a good cross-platform use case with lots of dependencies / edge cases).

**Comment by cojo** [comment] 2024-07-31 19:06
Put another way, it would be helpful if you can clarify how you would expect it to look if we want to use the build CLI for web, and skip over it for native, assuming that is the recommended path at this time.

Once we are able to test and verify that, we can probably help re: figuring out how to appropriately document this so that there are new developers potentially coming in and hitting the same issue (e.g. lots of previous Vercel users earlier in the thread that are presumably also still having to work around this).

My current sense is that our use of metro's static bundling for static sites for web might break if we try to ditch the plugin?  But you might know better than I would there (not sure if you're using metro and / or their static router mode as well for deploying web)

**Comment by mrjackdavis** [comment] 2024-09-16 03:18
Hey peeps,

I smashed into this issue just now. And after reading @cojo's fantastic assessment, I noted the problem is this plugin writes to disk. So I popped out a PR which just inlines the CSS 🤷 

Keen for feedback over there #2920

**Comment by natew** [comment] 2024-09-16 06:22
I've added two new settings and also added more delay after the initial css emit in v 1.111.2:

Thanks to https://github.com/tamagui/tamagui/pull/2920 if you add `TAMAGUI_METRO_INLINE_CSS=1` it will inline css which avoids the error.

Just want to test this. Actually didn't realize Metro may be inlining CSS always? This is sort of insane, I thought it was pulling it out into CSS if someone can confirm that.

I also added `TAMAGUI_METRO_CSS_EMIT_DELAY` you can see it like `TAMAGUI_METRO_CSS_EMIT_DELAY=2000` to increase the delay which may fix the issue as well.

Let me know if either of these works. Release is going out now should just be a few min.

**Comment by seeden** [comment] 2024-09-16 09:43
TAMAGUI_METRO_CSS_EMIT_DELAY did not fix it for me. I tried TAMAGUI_METRO_CSS_EMIT_DELAY=5000 as well

**Comment by natew** [comment] 2024-09-18 17:45
did `TAMAGUI_METRO_INLINE_CSS` work?

**Comment by natew** [comment] 2024-10-01 02:51
ok i've made this the default 83b9fca8abaf72eb9483b77fdcf0e9aab2566b66 for now even though inline css is not performant, you can disable it with TAMAGUI_METRO_INLINE_CSS=0, will try and get in touch with metro team soon. release going out now.

**Closed by natew** 2024-10-01 02:51 UTC
