### ISSUE TITLE
TS checks not working for tokens

### ISSUE THREAD

**Issue by vonovak** [tamagui/tamagui#1649] opened 2023-09-15 08:03 UTC
### Current Behavior

I expect TS to be fully aware of what tokens for color and etc I can use. However, it seems TS has very little idea of what values I can pass to `borderColor` or others.

Also, question: how is the `.tamagui` folder meant to be created? Is it necessary for correct type support?

### Expected Behavior

Note that I use 

```
  settings: {
    allowedStyleValues: 'strict',
  },
```

in Tamagui config.

I expect TS to be able to check if I pass an invalid value to a components such as here

```
const TransparentInput = styled(Input, {
  borderColor: 'transparent',
  borderWidth: 0,
  outlineColor: 'transparent',
  hoverStyle: {
    borderColor: 'transparent',
    outlineColor: '$someColorThatDoesNotExist',
    borderWidth: '$890',
  },
  focusStyle: {
    borderColor: 'transparent',
    outlineColor: 'someColorThatDoesNotExist',
    borderWidth: 0,
  },
});
```

### Tamagui Version

```markdown
1.65.1
```

not sure if that makes a difference, but I noticed that the `latest` tag on npm doesn't always point to the same version across packages.

you see, in the commit below, I used the `"upgrade": "manypkg upgrade tamagui && manypkg upgrade @tamagui && manypkg upgrade tamagui-loader && manypkg upgrade react-native-web-lite"` command to upgrade all tamagui packages and the result was `"@tamagui/themes": "^1.65.0"` but also `"@tamagui/shorthands": "^1.65.1"`

### Reproduction

https://github.com/vonovak/issue-template-webpack/commit/6902fd0427c360ca6a1d658830b9704784b181eb

clone, install, run `npm run dev` which generates the `.tamagui` folder

**Comment by JuanRdBO** [comment] 2023-09-15 17:51
I have the same issue/ concern with it. This prevents me to get fully confortable with tamagui because I never know which keys a certain component can accept

**Comment by natew** [comment] 2023-09-15 22:13
Oh that version mis-match is definitely causing it. We had a release that npm fudged causing version mis-matches, which causes everything to break. The latest versions fix it.

**Comment by natew** [comment] 2023-09-15 22:28
Hm looking into something now I see the starter having trouble

**Comment by natew** [comment] 2023-09-15 22:55
Thanks for the report, this was a regression and caused because our tests only covered changing both at once:

```
   allowedStyleValues: 'somewhat-strict',
   autocompleteSpecificTokens: 'except-special',
```

So I put those into our main test and fixed the issue so you can define only one. Next release fixes.

**Comment by natew** [comment] 2023-09-15 23:30
Fixed in the starter, lmk if not working. Sorry about that!

**Closed by natew** 2023-09-15 23:30 UTC
