### ISSUE TITLE
[Bug]: `<Theme />` component not updating all components within provider starting at `v1.105.x` & up

### ISSUE THREAD

**Issue by mvolonnino** [tamagui/tamagui#2856] opened 2024-08-15 22:00 UTC
Just backtracked from the latest version and on `1.104.2` it works as expected:

```tsx
import { type PropsWithChildren } from 'react';
import { TamaguiProvider as TMGUIProvider, Theme as TamaguiTheme } from 'tamagui';
import { ToastProvider, ToastViewport } from '@tamagui/toast';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { useTheming } from '@/theme/ThemeStore';
import tamaguiConfig from '@/theme/tamagui/tamagui.config';

export default function TamaguiProviders({ children }: PropsWithChildren) {
  const insets = useSafeAreaInsets();

  // themeName -> matches tamagui presets
  // colorMode -> 'light' | 'dark'
  const { colorMode, themeName } = useTheming();

  return (
    <TMGUIProvider config={tamaguiConfig} defaultTheme={colorMode}>
      <TamaguiTheme name={themeName}>
        <ToastProvider swipeDirection="vertical" duration={6000}>
          {children} // app renders here
          <ToastViewport
            top={insets.top + 5}
            right={insets.right}
            left={insets.left}
            multipleToasts
            flexDirection="column-reverse"
          />
        </ToastProvider>
      </TamaguiTheme>
    </TMGUIProvider>
  );
}
```

This code is used to wrap my root `<Slot />` component for Expo Router. I noticed that my theming on my app has been off since upgrading earlier from `1.103.3` to `1.108.3`

Some `styled` components would not update to reflect the `themeName` (base v3 config values ie. red, blue, etc) while others would - leaving some components getting updated to my current selection while others staying the selection that the app started up with.

If i close and re open (theme is persisted with async storage) when opening next, all theming would match my latest choice.

This seems to happen on any version above `1.104.2` with checking each _major_ iteration up until `1.108.3`, so it seems `1.105.0` to `1.108.3`.

Has anyone else run into this issue before?

**Comment by romain-spielmann** [comment] 2024-08-18 13:25
Ran into the same issue, downgrading to 1.104.2 seems to fix it.

**Comment by ed-00** [comment] 2024-08-19 15:21
Any fix other than down grading?

**Comment by leonardmq** [comment] 2024-08-27 19:13
May not be related to the same issue, but it sounds similar so might help other people who might find this thread.

On `1.109.3` and probably other versions, on iOS, changing the theme dynamically in the `Theme` provider causes only a few (random) components to render to match the new theme, while everything else stays on the previous theme. As you navigate back and forth, some components flip to the new theme while others never update. That was caused by `fastSchemeChange: true` in the default config (`@tamagui/config/v3`). Turning it off in my configuration solved the issue. 

I find it odd that `fastSchemeChange` is set to `true` in the default configuration as the [docs](https://tamagui.dev/docs/core/configuration) also mention it as being in beta and with known issues on iOS:
> (beta) On iOS, this enables a mode where Tamagui returns color values using DynamicColorIOS significantly speeding up dark/light re-renders. If you use theme inverse or manually change from light to dark without also changing the native color scheme, this will break. We're working on accounting for these last edge cases before removing the beta tag.

```tsx
import { createTamagui } from 'tamagui';
import { tokens, config as defaultConfig } from '@tamagui/config/v3';
import * as themes from './theme-output';

const config = createTamagui({
  ...defaultConfig,
  settings: {
    ...defaultConfig.settings,
    fastSchemeChange: false,
  },
  tokens,
  themes,
});
```

**Comment by mvolonnino** [comment] 2024-09-02 15:08
@leonardmq - that seems to have fixed the issue for me - updated to latest `1.110.1` and updated my config with the

```ts
...
settings: {
  fastSchemeChange: false
}
```

And seeing all the components render correctly with the desired selected color!

Thanks for the insight buddy! 🤝

**Comment by dieguezguille** [comment] 2024-09-15 21:17
I noticed this happening to me as well using either `<ThemeProvider />` and passing a `defaultTheme` directly or placing a  `<Theme/>` under it and passing a `theme` prop. I'm using v3 version of the config and the package version is 1.110.3. Already tried setting `fastSchemeChange` to `false` and rebuilt the app but still some components such as Buttons keep displaying the previous theme. Reloading the app applies the selected theme correctly. Any ideas?

**Comment by dieguezguille** [comment] 2024-09-23 18:44
> I noticed this happening to me as well using either `<ThemeProvider />` and passing a `defaultTheme` directly or placing a `<Theme/>` under it and passing a `theme` prop. I'm using v3 version of the config and the package version is 1.110.3. Already tried setting `fastSchemeChange` to `false` and rebuilt the app but still some components such as Buttons keep displaying the previous theme. Reloading the app applies the selected theme correctly. Any ideas?

Following up on this issue, I noticed that using component variants breaks the expected behaviour. The theme switches just fine if you pass props directly to the component instead of using variants. At least this was the case with `<Button />`

**Comment by bastischulz** [comment] 2024-09-24 09:29
It's broken for me too. I have a custom theme config, setting a $background color on a <YStack /> -> No Change.
<img width="431" alt="Screenshot 2024-09-24 at 11 25 55" src="https://github.com/user-attachments/assets/46926433-12f0-4f7a-89a0-53a63749b37c">

The name and color variable is clearly changing:
<img width="428" alt="Screenshot 2024-09-24 at 11 26 20" src="https://github.com/user-attachments/assets/e446bc37-08c4-4807-823c-36645c9d5ec9">

Theme Provider looks like this.
<img width="758" alt="Screenshot 2024-09-24 at 11 26 54" src="https://github.com/user-attachments/assets/5b29984d-254b-4544-aeec-221f38a2201a">

1.104.2 is working fine-ish (for the YStack at least) - In general not really because if I follow the setup steps from https://tamagui.dev/docs/guides/design-systems to add my own design system (or lets call it compiled components), many components don't change the theme either.

**Comment by buildnewapp** [comment] 2024-10-17 06:54
```
<Theme name="dark">
      <Button>I have the theme dark</Button>
      <Theme name="pink">
        <Button>I have the theme pink-dark</Button>
      </Theme>
    </Theme>
```



web is ok, but theme demo not work on ios !

After adding the fastSchemeChange configuration, the above code can be displayed as expected. 
Please fix it as soon as possible, this fixing method is not elegant.
```
import { config as configBase } from '@tamagui/config/v3'
import { createTamagui } from 'tamagui'

export const config = createTamagui({
  ...configBase,
  settings:{
    ...configBase.settings,
    fastSchemeChange:false
  }
})

export default config
```

**Comment by natew** [comment] 2024-10-21 23:59
Will look at this one next, sorry guys.

**Comment by natew** [comment] 2024-10-22 00:00
Can anyone verify if this is fixed on the latest? I did check a variety of settings and didn't see an issue, but it's possible it still is happening.

**Comment by natew** [comment] 2024-10-22 00:13
Ok tested this again and looks like we have fixed, very sorry for the regression! Let me know if still an issue with your config, I'm adding tests for both fastSchemeChange on and off

**Closed by natew** 2024-10-22 00:13 UTC

**Comment by andrewchester1** [comment] 2025-01-21 17:20
Seeing this in 1.122.6. In a "Settings" Tab Screen, the user can navigate to an "Appearance" screen where the user can change the color scheme. Everything seems to work when they switch themes, but when navigating back to the "Settings" Tab Screen, the components with variants did not switch to the correct them. Every other screen is fine, and components without using variants are fine. 

Seems like variants are not picking up the theme change, on previous rendered screens
